Microsoft Broadband Usage 2020 Data Processing
================
Cary K. Jim

``` r
library(tidyverse)
```

    ## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --

    ## v ggplot2 3.3.5     v purrr   0.3.4
    ## v tibble  3.1.6     v dplyr   1.0.7
    ## v tidyr   1.1.4     v stringr 1.4.0
    ## v readr   2.1.1     v forcats 0.5.1

    ## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(dplyr)
library(ggplot2)
library(readr)
library(stringr)
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

``` r
library(psych)
```

    ## 
    ## Attaching package: 'psych'

    ## The following objects are masked from 'package:ggplot2':
    ## 
    ##     %+%, alpha

``` r
library(readxl)
library(psychTools)
```

# Microsoft Broadband Usage Data

Data Source:<https://github.com/microsoft/USBroadbandUsagePercentages>

# Oct 2020 data

## County Level

``` r
microsoft_2020_county <- 'https://raw.githubusercontent.com/microsoft/USBroadbandUsagePercentages/master/dataset/broadband_data_2020October.csv'

# The regular reading will not work because of in-line text within the csv file in the 2020 dataset
usage_county_2020 <- read.csv(url(microsoft_2020_county), header = T, sep = ",", strip.white = TRUE, fileEncoding="UTF-8-BOM", na.strings = "-")

#' reload the usage data by skipping the top 18 rows (n = 3142)
usage_county_2020 <- read.csv(url(microsoft_2020_county), skip = 18, header = T, sep = ",", strip.white = TRUE, fileEncoding="UTF-8-BOM")
```

### Dataframe Overview

``` r
head(usage_county_2020)
```

    ##   ST COUNTY.ID    COUNTY.NAME BROADBAND.AVAILABILITY.PER.FCC BROADBAND.USAGE
    ## 1 AL      1001 Autauga County                         0.8057           0.391
    ## 2 AL      1003 Baldwin County                         0.8362           0.452
    ## 3 AL      1005 Barbour County                         0.6891           0.324
    ## 4 AL      1007    Bibb County                         0.3368           0.136
    ## 5 AL      1009  Blount County                          0.758           0.199
    ## 6 AL      1011 Bullock County                         0.9363           0.157

``` r
str(usage_county_2020)
```

    ## 'data.frame':    3142 obs. of  5 variables:
    ##  $ ST                            : chr  "AL" "AL" "AL" "AL" ...
    ##  $ COUNTY.ID                     : int  1001 1003 1005 1007 1009 1011 1013 1015 1017 1019 ...
    ##  $ COUNTY.NAME                   : chr  "Autauga County" "Baldwin County" "Barbour County" "Bibb County" ...
    ##  $ BROADBAND.AVAILABILITY.PER.FCC: chr  "0.8057" "0.8362" "0.6891" "0.3368" ...
    ##  $ BROADBAND.USAGE               : chr  "0.391" "0.452" "0.324" "0.136" ...

Notice a few things from looking at the information. COUNTY.ID was
loaded as integer,‘BROADBAND.AVAILABILITY.PER.FCC’ & ‘BROADBAND.USAGE’
was loaded as characters. We have to correct the data types before next
step.

``` r
#Rename columns to make time frame explicit in the variables 
usage_county_2020 <- usage_county_2020 %>%
  rename(FCC2019_AVAIL = BROADBAND.AVAILABILITY.PER.FCC,
         USAGE_2020 = BROADBAND.USAGE)
```

``` r
#Convert the columns to number if read in as characters
usage_county_2020[4:5] <- lapply(usage_county_2020[4:5], as.numeric)
```

    ## Warning in lapply(usage_county_2020[4:5], as.numeric): NAs introduced by
    ## coercion

    ## Warning in lapply(usage_county_2020[4:5], as.numeric): NAs introduced by
    ## coercion

``` r
#Then, convert the COUNTY.ID to character 
usage_county_2020[2] <- as.character(usage_county_2020$COUNTY.ID)
# For a proper FIPS, there should be leading zero to it. For now, I'm ignoring this matter and will handle it later.
```

### Review data type after change

``` r
str(usage_county_2020)
```

    ## 'data.frame':    3142 obs. of  5 variables:
    ##  $ ST           : chr  "AL" "AL" "AL" "AL" ...
    ##  $ COUNTY.ID    : chr  "1001" "1003" "1005" "1007" ...
    ##  $ COUNTY.NAME  : chr  "Autauga County" "Baldwin County" "Barbour County" "Bibb County" ...
    ##  $ FCC2019_AVAIL: num  0.806 0.836 0.689 0.337 0.758 ...
    ##  $ USAGE_2020   : num  0.391 0.452 0.324 0.136 0.199 0.157 0.183 0.419 0.501 0.125 ...

### Missing values in the Oct 2020 County Level Usage Dataset

``` r
#There are 20 County without either Broadband Availability information or Usage Information 
usage_county_2020[!complete.cases(usage_county_2020), ]
```

    ##      ST COUNTY.ID                COUNTY.NAME FCC2019_AVAIL USAGE_2020
    ## 68   AK      2013     Aleutians East Borough            NA      0.066
    ## 69   AK      2016 Aleutians West Census Area            NA      0.023
    ## 71   AK      2050         Bethel Census Area            NA      0.050
    ## 72   AK      2060        Bristol Bay Borough            NA      0.054
    ## 74   AK      2070     Dillingham Census Area            NA      0.052
    ## 82   AK      2164 Lake and Peninsula Borough            NA      0.161
    ## 93   AK      2158       Kusilvak Census Area            NA      0.088
    ## 95   AK      2282   Yakutat City and Borough            NA      0.024
    ## 1657 NE     31005              Arthur County        0.7559         NA
    ## 1658 NE     31007              Banner County        0.9879         NA
    ## 1713 NE     31117           McPherson County        0.5182         NA
    ## 2243 OR     41069             Wheeler County            NA      0.149
    ## 2658 TX     48269                King County        0.4853         NA
    ## 2922 VA     51580             Covington city        0.9969         NA
    ## 2924 VA     51595               Emporia city        0.9600         NA
    ## 2925 VA     51600               Fairfax city        0.9985         NA
    ## 2933 VA     51678             Lexington city        0.9612         NA
    ## 2936 VA     51685         Manassas Park city        0.9843         NA
    ## 2937 VA     51690          Martinsville city        0.9871         NA
    ## 2952 VA     51830          Williamsburg city        0.7844         NA

### Number of Countes by State

``` r
usage_county_2020 %>% count(ST)
```

    ##    ST   n
    ## 1  AK  29
    ## 2  AL  67
    ## 3  AR  75
    ## 4  AZ  15
    ## 5  CA  58
    ## 6  CO  64
    ## 7  CT   8
    ## 8  DC   1
    ## 9  DE   3
    ## 10 FL  67
    ## 11 GA 159
    ## 12 HI   5
    ## 13 IA  99
    ## 14 ID  44
    ## 15 IL 102
    ## 16 IN  92
    ## 17 KS 105
    ## 18 KY 120
    ## 19 LA  64
    ## 20 MA  14
    ## 21 MD  24
    ## 22 ME  16
    ## 23 MI  83
    ## 24 MN  87
    ## 25 MO 115
    ## 26 MS  82
    ## 27 MT  56
    ## 28 NC 100
    ## 29 ND  53
    ## 30 NE  93
    ## 31 NH  10
    ## 32 NJ  21
    ## 33 NM  33
    ## 34 NV  17
    ## 35 NY  62
    ## 36 OH  88
    ## 37 OK  77
    ## 38 OR  36
    ## 39 PA  67
    ## 40 RI   5
    ## 41 SC  46
    ## 42 SD  66
    ## 43 TN  95
    ## 44 TX 254
    ## 45 UT  29
    ## 46 VA 133
    ## 47 VT  14
    ## 48 WA  39
    ## 49 WI  72
    ## 50 WV  55
    ## 51 WY  23

## ZIP Code Level

``` r
microsoft_2020_ZIP <- "https://raw.githubusercontent.com/microsoft/USBroadbandUsagePercentages/master/dataset/broadband_data_zipcode.csv"
usage_ZIP_2020 <- read.csv(url(microsoft_2020_ZIP), header = T, sep = ",", strip.white = TRUE, fileEncoding="UTF-8-BOM")
```

### Dataframe Overview

``` r
head(usage_ZIP_2020)
```

    ##   ST   COUNTY.NAME COUNTY.ID POSTAL.CODE BROADBAND.USAGE ERROR.RANGE..MAE......
    ## 1 SC     Abbeville     45001       29639           0.948                  0.034
    ## 2 SC     Abbeville     45001       29620           0.398                  0.002
    ## 3 SC     Abbeville     45001       29659           0.206                  0.152
    ## 4 SC     Abbeville     45001       29638           0.369                  0.010
    ## 5 SC     Abbeville     45001       29628           0.221                  0.014
    ## 6 LA Acadia Parish     22001       70516           0.032                  0.041
    ##   ERROR.RANGE..95.......    MSD
    ## 1                  0.110  0.002
    ## 2                  0.007  0.000
    ## 3                  0.608  0.043
    ## 4                  0.031 -0.001
    ## 5                  0.043  0.000
    ## 6                  0.136  0.004

``` r
#Rename columns to make time frame explicit in the variables and fixed the long names 
usage_ZIP_2020 <- usage_ZIP_2020 %>% 
  rename(USAGE_2020 = BROADBAND.USAGE)

colnames(usage_ZIP_2020)[6:7] <- c("MAE", "Percentile")
```

### Review data types

``` r
str(usage_ZIP_2020)
```

    ## 'data.frame':    32735 obs. of  8 variables:
    ##  $ ST         : chr  "SC" "SC" "SC" "SC" ...
    ##  $ COUNTY.NAME: chr  "Abbeville" "Abbeville" "Abbeville" "Abbeville" ...
    ##  $ COUNTY.ID  : int  45001 45001 45001 45001 45001 22001 22001 22001 22001 22001 ...
    ##  $ POSTAL.CODE: int  29639 29620 29659 29638 29628 70516 70559 70531 70578 70537 ...
    ##  $ USAGE_2020 : num  0.948 0.398 0.206 0.369 0.221 0.032 0.091 0.053 0.201 0.181 ...
    ##  $ MAE        : num  0.034 0.002 0.152 0.01 0.014 0.041 0.014 0.023 0.002 0.05 ...
    ##  $ Percentile : num  0.11 0.007 0.608 0.031 0.043 0.136 0.043 0.072 0.007 0.17 ...
    ##  $ MSD        : num  0.002 0 0.043 -0.001 0 0.004 0 0 0 0.007 ...

For the ZIP level dataset, the usage information and its error range
were in the correct form as numeric. For COUNTY.ID and POSTAL.CODE, they
need to be converted to characters. Also, POSTAL.CODE will be renamed to
ZIP for ease of use at a later time.

``` r
usage_ZIP_2020[3:4] <- lapply(usage_ZIP_2020[3:4], as.character)
```

Rename the POSTAL.CODE column to ZIP

``` r
colnames(usage_ZIP_2020)[4] <- "ZIP"
```

### Review data type after conversion

``` r
str(usage_ZIP_2020)
```

    ## 'data.frame':    32735 obs. of  8 variables:
    ##  $ ST         : chr  "SC" "SC" "SC" "SC" ...
    ##  $ COUNTY.NAME: chr  "Abbeville" "Abbeville" "Abbeville" "Abbeville" ...
    ##  $ COUNTY.ID  : chr  "45001" "45001" "45001" "45001" ...
    ##  $ ZIP        : chr  "29639" "29620" "29659" "29638" ...
    ##  $ USAGE_2020 : num  0.948 0.398 0.206 0.369 0.221 0.032 0.091 0.053 0.201 0.181 ...
    ##  $ MAE        : num  0.034 0.002 0.152 0.01 0.014 0.041 0.014 0.023 0.002 0.05 ...
    ##  $ Percentile : num  0.11 0.007 0.608 0.031 0.043 0.136 0.043 0.072 0.007 0.17 ...
    ##  $ MSD        : num  0.002 0 0.043 -0.001 0 0.004 0 0 0 0.007 ...

### Check Missing Values

``` r
usage_ZIP_2020[!complete.cases(usage_ZIP_2020), ]
```

    ## [1] ST          COUNTY.NAME COUNTY.ID   ZIP         USAGE_2020  MAE        
    ## [7] Percentile  MSD        
    ## <0 rows> (or 0-length row.names)

### Check Duplicated Rows

``` r
sum(duplicated(usage_ZIP_2020$ZIP))
```

    ## [1] 82

``` r
usage_ZIP_2020$ZIP[duplicated(usage_ZIP_2020$ZIP)]
```

    ##  [1] "99554" "99658" "99585" "99644" "99620" "99563" "99632" "99615" "99650"
    ## [10] "99604" "99643" "99581" "99550" "99624" "99662" "99666" "99657" "57065"
    ## [19] "57017" "57024" "57756" "57794" "57764" "57716" "57752" "57770" "57028"
    ## [28] "57772" "56534" "56437" "56361" "56389" "56347" "56567" "56336" "56524"
    ## [37] "56440" "56572" "56446" "56573" "56318" "56515" "56527" "56533" "56479"
    ## [46] "56518" "56571" "56537" "56324" "56588" "56434" "56528" "56551" "56453"
    ## [55] "56438" "56587" "56576" "56586" "55071" "55001" "55055" "55038" "55025"
    ## [64] "56060" "55047" "55043" "55016" "55129" "55003" "56120" "55073" "55115"
    ## [73] "55125" "56062" "56081" "56056" "55128" "55042" "55090" "56022" "55082"
    ## [82] "56160"

``` r
usage_ZIP_2020 %>% filter(ZIP == "99554" | ZIP == "99658") 
```

    ##   ST           COUNTY.NAME COUNTY.ID   ZIP USAGE_2020   MAE Percentile   MSD
    ## 1 AK Kodiak Island Borough      2150 99554      0.039 0.065      0.228 0.013
    ## 2 AK Kodiak Island Borough      2158 99554      0.039 0.065      0.228 0.013
    ## 3 AK Kodiak Island Borough      2150 99658      0.000 0.065      0.228 0.013
    ## 4 AK Kodiak Island Borough      2158 99658      0.000 0.065      0.228 0.013

``` r
# This county has two ID in which the 2150 is the correct COUNTY.ID as of 2010. County.ID 2158 is an old COUNTY.ID. 
```

Reference to Census Technical Documentation on County Changes in 2010.
<https://www.census.gov/programs-surveys/geography/technical-documentation/county-changes.2010.html>

``` r
usage_ZIP_2020 <- usage_ZIP_2020[!(usage_ZIP_2020$COUNTY.ID == "2158"),]
# The resulting dataframe is 32718 rows 
```

### Re-check duplicated rows after handling the Kodiak Island Borough records

``` r
usage_ZIP_2020$ZIP[duplicated(usage_ZIP_2020$ZIP)]
```

    ##  [1] "57065" "57017" "57024" "57756" "57794" "57764" "57716" "57752" "57770"
    ## [10] "57028" "57772" "56534" "56437" "56361" "56389" "56347" "56567" "56336"
    ## [19] "56524" "56440" "56572" "56446" "56573" "56318" "56515" "56527" "56533"
    ## [28] "56479" "56518" "56571" "56537" "56324" "56588" "56434" "56528" "56551"
    ## [37] "56453" "56438" "56587" "56576" "56586" "55071" "55001" "55055" "55038"
    ## [46] "55025" "56060" "55047" "55043" "55016" "55129" "55003" "56120" "55073"
    ## [55] "55115" "55125" "56062" "56081" "56056" "55128" "55042" "55090" "56022"
    ## [64] "55082" "56160"

``` r
usage_ZIP_2020 %>% filter(ZIP == "57065" | ZIP == "57017") 
```

    ##   ST COUNTY.NAME COUNTY.ID   ZIP USAGE_2020   MAE Percentile   MSD
    ## 1 SD       Moody     46102 57065      0.083 0.065      0.228 0.013
    ## 2 SD       Moody     46101 57065      0.083 0.065      0.228 0.013
    ## 3 SD       Moody     46102 57017      0.078 0.020      0.061 0.000
    ## 4 SD       Moody     46101 57017      0.078 0.020      0.061 0.000

Moody County is not listed in the County Name Change webpage on Census.
The U.S. Census Quick Facts is used to check the current County ID for
Moody, in SD.
<https://www.census.gov/quickfacts/fact/table/moodycountysouthdakota,US/PST045221>
The correct County ID for Moody, SD is 46101.

``` r
usage_ZIP_2020 <- usage_ZIP_2020[!(usage_ZIP_2020$COUNTY.ID == "46102"),]
# The resulting dataframe is 32707 rows 
```

### Re-check duplicated rows after handling the Moody County records

``` r
usage_ZIP_2020$ZIP[duplicated(usage_ZIP_2020$ZIP)]
```

    ##  [1] "56534" "56437" "56361" "56389" "56347" "56567" "56336" "56524" "56440"
    ## [10] "56572" "56446" "56573" "56318" "56515" "56527" "56533" "56479" "56518"
    ## [19] "56571" "56537" "56324" "56588" "56434" "56528" "56551" "56453" "56438"
    ## [28] "56587" "56576" "56586" "55071" "55001" "55055" "55038" "55025" "56060"
    ## [37] "55047" "55043" "55016" "55129" "55003" "56120" "55073" "55115" "55125"
    ## [46] "56062" "56081" "56056" "55128" "55042" "55090" "56022" "55082" "56160"

There is still 54 rows of records that has duplicated county by ZIP.
Therefore, a subset of the dataframe is used.

``` r
subset(usage_ZIP_2020,duplicated(ZIP))
```

    ##       ST COUNTY.NAME COUNTY.ID   ZIP USAGE_2020   MAE Percentile    MSD
    ## 29164 MN        Todd     27111 56534      0.138 0.027      0.086  0.001
    ## 29166 MN        Todd     27111 56437      0.294 0.023      0.072  0.000
    ## 29168 MN        Todd     27111 56361      0.460 0.014      0.043  0.000
    ## 29170 MN        Todd     27111 56389      0.000 0.152      0.608  0.043
    ## 29172 MN        Todd     27111 56347      0.167 0.006      0.018 -0.001
    ## 29174 MN        Todd     27111 56567      0.287 0.010      0.031 -0.001
    ## 29176 MN        Todd     27111 56336      0.064 0.020      0.061  0.000
    ## 29178 MN        Todd     27111 56524      0.111 0.041      0.136  0.004
    ## 29180 MN        Todd     27111 56440      0.133 0.023      0.072  0.000
    ## 29182 MN        Todd     27111 56572      0.389 0.006      0.018 -0.001
    ## 29184 MN        Todd     27111 56446      0.242 0.020      0.061  0.000
    ## 29186 MN        Todd     27111 56573      0.519 0.006      0.018 -0.001
    ## 29188 MN        Todd     27111 56318      0.110 0.027      0.086  0.001
    ## 29190 MN        Todd     27111 56515      0.458 0.010      0.031 -0.001
    ## 29192 MN        Todd     27111 56527      0.486 0.034      0.110  0.002
    ## 29194 MN        Todd     27111 56533      0.056 0.083      0.302  0.021
    ## 29196 MN        Todd     27111 56479      0.655 0.006      0.018 -0.001
    ## 29198 MN        Todd     27111 56518      0.269 0.065      0.228  0.013
    ## 29200 MN        Todd     27111 56571      0.502 0.018      0.054  0.000
    ## 29202 MN        Todd     27111 56537      0.739 0.002      0.005  0.000
    ## 29204 MN        Todd     27111 56324      0.188 0.027      0.086  0.001
    ## 29206 MN        Todd     27111 56588      0.288 0.041      0.136  0.004
    ## 29208 MN        Todd     27111 56434      0.002 0.110      0.406  0.031
    ## 29210 MN        Todd     27111 56528      0.217 0.018      0.054  0.000
    ## 29212 MN        Todd     27111 56551      0.119 0.016      0.048  0.000
    ## 29214 MN        Todd     27111 56453      0.322 0.034      0.110  0.002
    ## 29216 MN        Todd     27111 56438      0.070 0.010      0.031 -0.001
    ## 29218 MN        Todd     27111 56587      0.339 0.020      0.061  0.000
    ## 29220 MN        Todd     27111 56576      0.052 0.041      0.136  0.004
    ## 29222 MN        Todd     27111 56586      0.182 0.018      0.054  0.000
    ## 30643 MN  Washington     27163 55071      0.313 0.006      0.018 -0.001
    ## 30645 MN  Washington     27163 55001      0.200 0.010      0.031 -0.001
    ## 30647 MN  Washington     27163 55055      0.446 0.010      0.031 -0.001
    ## 30649 MN  Washington     27163 55038      0.395 0.002      0.007  0.000
    ## 30651 MN  Washington     27163 55025      1.000 0.002      0.005  0.000
    ## 30653 MN  Washington     27163 56060      0.222 0.065      0.228  0.013
    ## 30655 MN  Washington     27163 55047      0.251 0.014      0.043  0.000
    ## 30657 MN  Washington     27163 55043      0.249 0.010      0.031 -0.001
    ## 30659 MN  Washington     27163 55016      0.478 0.001      0.004  0.000
    ## 30661 MN  Washington     27163 55129      0.675 0.002      0.005  0.000
    ## 30663 MN  Washington     27163 55003      0.254 0.014      0.043  0.000
    ## 30665 MN  Washington     27163 56120      0.061 0.027      0.086  0.001
    ## 30667 MN  Washington     27163 55073      0.124 0.010      0.031 -0.001
    ## 30669 MN  Washington     27163 55115      0.347 0.004      0.013  0.000
    ## 30671 MN  Washington     27163 55125      1.000 0.001      0.003  0.000
    ## 30673 MN  Washington     27163 56062      0.210 0.010      0.031 -0.001
    ## 30675 MN  Washington     27163 56081      0.139 0.006      0.018 -0.001
    ## 30677 MN  Washington     27163 56056      0.063 0.152      0.608  0.043
    ## 30679 MN  Washington     27163 55128      0.840 0.001      0.004  0.000
    ## 30681 MN  Washington     27163 55042      0.500 0.004      0.013  0.000
    ## 30683 MN  Washington     27163 55090      0.198 0.065      0.228  0.013
    ## 30685 MN  Washington     27163 56022      0.039 0.152      0.608  0.043
    ## 30687 MN  Washington     27163 55082      0.787 0.001      0.003  0.000
    ## 30689 MN  Washington     27163 56160      0.000 0.110      0.406  0.031

There are two more counties that have similar issues.

``` r
usage_ZIP_2020 %>% filter(ZIP == "56534" | ZIP == "56437") 
```

    ##   ST COUNTY.NAME COUNTY.ID   ZIP USAGE_2020   MAE Percentile   MSD
    ## 1 MN        Todd     27153 56534      0.138 0.027      0.086 0.001
    ## 2 MN        Todd     27111 56534      0.138 0.027      0.086 0.001
    ## 3 MN        Todd     27153 56437      0.294 0.023      0.072 0.000
    ## 4 MN        Todd     27111 56437      0.294 0.023      0.072 0.000

Todd County, MN should be COUNTY.ID == 27153

``` r
usage_ZIP_2020 %>% filter(ZIP == "55082" | ZIP == "56160") 
```

    ##   ST COUNTY.NAME COUNTY.ID   ZIP USAGE_2020   MAE Percentile   MSD
    ## 1 MN  Washington     27165 55082      0.787 0.001      0.003 0.000
    ## 2 MN  Washington     27163 55082      0.787 0.001      0.003 0.000
    ## 3 MN  Washington     27165 56160      0.000 0.110      0.406 0.031
    ## 4 MN  Washington     27163 56160      0.000 0.110      0.406 0.031

Washington County, MN should be 27163

``` r
usage_ZIP_2020 <- usage_ZIP_2020[!(usage_ZIP_2020$COUNTY.ID == "27111"),]
# The resulting dataframe is 32677 rows after removing Todd duplicates
usage_ZIP_2020 <- usage_ZIP_2020[!(usage_ZIP_2020$COUNTY.ID == "27165"),]
# The resulting dataframe is 32653 rows after removing Washington County duplicates
```

### Re-check duplicated record

``` r
usage_ZIP_2020$ZIP[duplicated(usage_ZIP_2020$ZIP)]
```

    ## character(0)

The duplicated records have been removed. The distinct rows of ZIP code
is 32653 in the ZIP 2020 usage data file.

### Counts of County and State by ZIP

``` r
usage_ZIP_2020 %>% count(ST)
```

    ##    ST    n
    ## 1  AK  234
    ## 2  AL  638
    ## 3  AR  589
    ## 4  AZ  399
    ## 5  CA 1736
    ## 6  CO  514
    ## 7  CT  278
    ## 8  DC   30
    ## 9  DE   64
    ## 10 FL  977
    ## 11 GA  725
    ## 12 HI   92
    ## 13 IA  932
    ## 14 ID  277
    ## 15 IL 1378
    ## 16 IN  769
    ## 17 KS  693
    ## 18 KY  761
    ## 19 LA  511
    ## 20 MA  533
    ## 21 MD  466
    ## 22 ME  429
    ## 23 MI  974
    ## 24 MN  881
    ## 25 MO 1016
    ## 26 MS  419
    ## 27 MT  361
    ## 28 NC  805
    ## 29 ND  379
    ## 30 NE  581
    ## 31 NH  247
    ## 32 NJ  589
    ## 33 NM  361
    ## 34 NV  172
    ## 35 NY 1757
    ## 36 OH 1187
    ## 37 OK  646
    ## 38 OR  413
    ## 39 PA 1781
    ## 40 RI   77
    ## 41 SC  421
    ## 42 SD  372
    ## 43 TN  622
    ## 44 TX 1911
    ## 45 UT  286
    ## 46 VA  887
    ## 47 VT  252
    ## 48 WA  588
    ## 49 WI  772
    ## 50 WV  702
    ## 51 WY  169

``` r
usage_ZIP_2020 %>% count(COUNTY.ID)
```

    ##      COUNTY.ID   n
    ## 1        10001  16
    ## 2        10003  26
    ## 3        10005  22
    ## 4         1001   6
    ## 5         1003  22
    ## 6         1005   4
    ## 7         1007   8
    ## 8         1009   8
    ## 9         1011   3
    ## 10        1013   4
    ## 11        1015  12
    ## 12        1017   4
    ## 13        1019   4
    ## 14        1021   7
    ## 15        1023  10
    ## 16        1025   9
    ## 17        1027   5
    ## 18        1029   4
    ## 19        1031   5
    ## 20        1033   5
    ## 21        1035   5
    ## 22        1037   5
    ## 23        1039  10
    ## 24        1041   6
    ## 25        1043  12
    ## 26        1045   7
    ## 27        1047   8
    ## 28        1049  15
    ## 29        1051   9
    ## 30        1053   4
    ## 31        1055  11
    ## 32        1057   6
    ## 33        1059   7
    ## 34        1061   8
    ## 35        1063   4
    ## 36        1065   5
    ## 37        1067   5
    ## 38        1069  11
    ## 39        1071  17
    ## 40        1073  53
    ## 41        1075   6
    ## 42        1077   8
    ## 43        1079   6
    ## 44        1081  11
    ## 45        1083   9
    ## 46        1085   5
    ## 47        1087   6
    ## 48        1089  22
    ## 49        1091   9
    ## 50        1093   6
    ## 51        1095   9
    ## 52        1097  36
    ## 53        1099  11
    ## 54       11001  30
    ## 55        1101  19
    ## 56        1103   9
    ## 57        1105   2
    ## 58        1107   5
    ## 59        1109   7
    ## 60        1111   5
    ## 61        1113   8
    ## 62        1115  12
    ## 63        1117  16
    ## 64        1119   8
    ## 65        1121   9
    ## 66        1123   5
    ## 67        1125  18
    ## 68        1127  13
    ## 69        1129  14
    ## 70        1131   9
    ## 71        1133   7
    ## 72       12001  19
    ## 73       12003   4
    ## 74       12005  12
    ## 75       12007   5
    ## 76       12009  27
    ## 77       12011  53
    ## 78       12013   4
    ## 79       12015  13
    ## 80       12017  13
    ## 81       12019   7
    ## 82       12021  21
    ## 83       12023   5
    ## 84       12027   3
    ## 85       12029   4
    ## 86       12031  34
    ## 87       12033  17
    ## 88       12035   4
    ## 89       12037   4
    ## 90       12039   7
    ## 91       12041   2
    ## 92       12043   2
    ## 93       12045   2
    ## 94       12047   3
    ## 95       12049   4
    ## 96       12051   3
    ## 97       12053  10
    ## 98       12055   8
    ## 99       12057  53
    ## 100      12059   2
    ## 101      12061   9
    ## 102      12063  12
    ## 103      12065   3
    ## 104      12067   1
    ## 105      12069  24
    ## 106      12071  36
    ## 107      12073  10
    ## 108      12075   9
    ## 109      12077   2
    ## 110      12079   4
    ## 111      12081  18
    ## 112      12083  25
    ## 113      12085   7
    ## 114      12086  78
    ## 115      12087   9
    ## 116      12089   5
    ## 117      12091  14
    ## 118      12093   2
    ## 119      12095  44
    ## 120      12097  12
    ## 121      12099  52
    ## 122      12101  23
    ## 123      12103  48
    ## 124      12105  38
    ## 125      12107  14
    ## 126      12109  10
    ## 127      12111  14
    ## 128      12113   8
    ## 129      12115  24
    ## 130      12117  13
    ## 131      12119   9
    ## 132      12121   6
    ## 133      12123   4
    ## 134      12125   3
    ## 135      12127  26
    ## 136      12129   4
    ## 137      12131   7
    ## 138      12133   5
    ## 139      13001   3
    ## 140      13003   3
    ## 141      13005   1
    ## 142      13007   1
    ## 143      13009   2
    ## 144      13011   3
    ## 145      13013   4
    ## 146      13015   8
    ## 147      13017   1
    ## 148      13019   4
    ## 149      13021  10
    ## 150      13023   1
    ## 151      13025   4
    ## 152      13027   4
    ## 153      13029   3
    ## 154      13031   6
    ## 155      13033   4
    ## 156      13035   3
    ## 157      13037   4
    ## 158      13039   6
    ## 159      13043   2
    ## 160      13045   9
    ## 161      13047   2
    ## 162      13049   2
    ## 163      13051  13
    ## 164      13053   2
    ## 165      13055   4
    ## 166      13057   7
    ## 167      13059   7
    ## 168      13061   3
    ## 169      13063   9
    ## 170      13065   4
    ## 171      13067  17
    ## 172      13069   6
    ## 173      13071   7
    ## 174      13073   6
    ## 175      13075   4
    ## 176      13077   7
    ## 177      13079   3
    ## 178      13081   2
    ## 179      13083   3
    ## 180      13085   1
    ## 181      13087   5
    ## 182      13089  28
    ## 183      13091   4
    ## 184      13093   5
    ## 185      13095   4
    ## 186      13097   4
    ## 187      13099   3
    ## 188      13101   1
    ## 189      13103   7
    ## 190      13105   3
    ## 191      13107   7
    ## 192      13109   3
    ## 193      13111   5
    ## 194      13113   5
    ## 195      13115   7
    ## 196      13117   3
    ## 197      13119   4
    ## 198      13121  36
    ## 199      13123   3
    ## 200      13125   2
    ## 201      13127   6
    ## 202      13129   6
    ## 203      13131   3
    ## 204      13133   4
    ## 205      13135  16
    ## 206      13137   5
    ## 207      13139  10
    ## 208      13141   1
    ## 209      13143   3
    ## 210      13145   8
    ## 211      13147   2
    ## 212      13149   1
    ## 213      13151   5
    ## 214      13153   8
    ## 215      13155   2
    ## 216      13157   8
    ## 217      13159   5
    ## 218      13161   2
    ## 219      13163   7
    ## 220      13165   2
    ## 221      13167   2
    ## 222      13169   2
    ## 223      13171   2
    ## 224      13173   2
    ## 225      13175   8
    ## 226      13177   2
    ## 227      13179   7
    ## 228      13181   1
    ## 229      13183   1
    ## 230      13185   9
    ## 231      13187   1
    ## 232      13189   2
    ## 233      13191   3
    ## 234      13193   4
    ## 235      13195   4
    ## 236      13197   3
    ## 237      13199   6
    ## 238      13201   1
    ## 239      13205   4
    ## 240      13207   3
    ## 241      13209   5
    ## 242      13211   4
    ## 243      13213   4
    ## 244      13215   8
    ## 245      13217   4
    ## 246      13219   3
    ## 247      13221   5
    ## 248      13223   3
    ## 249      13225   2
    ## 250      13227   4
    ## 251      13229   4
    ## 252      13231   5
    ## 253      13233   3
    ## 254      13235   1
    ## 255      13237   1
    ## 256      13239   1
    ## 257      13241   7
    ## 258      13243   3
    ## 259      13245   9
    ## 260      13247   3
    ## 261      13249   1
    ## 262      13251   4
    ## 263      13253   2
    ## 264      13255   3
    ## 265      13257   3
    ## 266      13259   4
    ## 267      13261   7
    ## 268      13263   4
    ## 269      13265   2
    ## 270      13267   5
    ## 271      13269   3
    ## 272      13271   6
    ## 273      13273   4
    ## 274      13275   8
    ## 275      13277   5
    ## 276      13279   2
    ## 277      13281   2
    ## 278      13283   1
    ## 279      13285   4
    ## 280      13287   3
    ## 281      13289   3
    ## 282      13291   2
    ## 283      13293   3
    ## 284      13295   6
    ## 285      13297   5
    ## 286      13299   4
    ## 287      13301   4
    ## 288      13303   6
    ## 289      13305   4
    ## 290      13307   2
    ## 291      13309   2
    ## 292      13311   3
    ## 293      13313   6
    ## 294      13315   5
    ## 295      13317   3
    ## 296      13319   5
    ## 297      13321   5
    ## 298      15001  28
    ## 299      15003  33
    ## 300      15005   1
    ## 301      15007  16
    ## 302      15009  14
    ## 303      16001  15
    ## 304      16003   4
    ## 305      16005  10
    ## 306      16007   9
    ## 307      16009   6
    ## 308      16011   9
    ## 309      16013   7
    ## 310      16015   6
    ## 311      16017  15
    ## 312      16019   9
    ## 313      16021   4
    ## 314      16023   3
    ## 315      16025   3
    ## 316      16027  11
    ## 317      16029   3
    ## 318      16031   6
    ## 319      16033   2
    ## 320      16035   6
    ## 321      16037   5
    ## 322      16039   6
    ## 323      16041   6
    ## 324      16043   7
    ## 325      16045   4
    ## 326      16047   4
    ## 327      16049  12
    ## 328      16051   8
    ## 329      16053   3
    ## 330      16055  12
    ## 331      16057  12
    ## 332      16059   9
    ## 333      16061   4
    ## 334      16063   3
    ## 335      16065   3
    ## 336      16067   3
    ## 337      16069   4
    ## 338      16071   2
    ## 339      16073   5
    ## 340      16075   3
    ## 341      16077   3
    ## 342      16079  12
    ## 343      16081   4
    ## 344      16083   8
    ## 345      16085   4
    ## 346      16087   3
    ## 347      17001  16
    ## 348      17003   6
    ## 349      17005   7
    ## 350      17007   5
    ## 351      17009   3
    ## 352      17011  24
    ## 353      17013   8
    ## 354      17015   7
    ## 355      17017   5
    ## 356      17019  29
    ## 357      17021  13
    ## 358      17023   6
    ## 359      17025   6
    ## 360      17027  11
    ## 361      17029   6
    ## 362      17031 163
    ## 363      17033   7
    ## 364      17035   6
    ## 365      17037  13
    ## 366      17039   8
    ## 367      17041   9
    ## 368      17043  36
    ## 369      17045   8
    ## 370      17047   4
    ## 371      17049   8
    ## 372      17051   9
    ## 373      17053   9
    ## 374      17055  16
    ## 375      17057  20
    ## 376      17059   6
    ## 377      17061  10
    ## 378      17063   9
    ## 379      17065   4
    ## 380      17067  15
    ## 381      17069   4
    ## 382      17071   8
    ## 383      17073  15
    ## 384      17075  20
    ## 385      17077  15
    ## 386      17079   7
    ## 387      17081  11
    ## 388      17083   6
    ## 389      17085   9
    ## 390      17087   8
    ## 391      17089  22
    ## 392      17091  16
    ## 393      17093   7
    ## 394      17095  16
    ## 395      17097  27
    ## 396      17099  24
    ## 397      17101   4
    ## 398      17103  13
    ## 399      17105  17
    ## 400      17107  14
    ## 401      17109  11
    ## 402      17111  19
    ## 403      17113  25
    ## 404      17115  16
    ## 405      17117  20
    ## 406      17119  27
    ## 407      17121  11
    ## 408      17123   8
    ## 409      17125   9
    ## 410      17127   4
    ## 411      17129   5
    ## 412      17131  11
    ## 413      17133   6
    ## 414      17135  17
    ## 415      17137   9
    ## 416      17139   5
    ## 417      17141  16
    ## 418      17143  25
    ## 419      17145   5
    ## 420      17147  10
    ## 421      17149  15
    ## 422      17151   2
    ## 423      17153   8
    ## 424      17155   7
    ## 425      17157  14
    ## 426      17159   6
    ## 427      17161  17
    ## 428      17163  27
    ## 429      17165   7
    ## 430      17167  25
    ## 431      17169   6
    ## 432      17171   4
    ## 433      17173  13
    ## 434      17175   6
    ## 435      17177  13
    ## 436      17179  15
    ## 437      17181   7
    ## 438      17183  23
    ## 439      17185   4
    ## 440      17187   9
    ## 441      17189  10
    ## 442      17191  12
    ## 443      17193   9
    ## 444      17195  12
    ## 445      17197  31
    ## 446      17199  11
    ## 447      17201  20
    ## 448      17203  11
    ## 449      18001   4
    ## 450      18003  27
    ## 451      18005   8
    ## 452      18007   6
    ## 453      18009   2
    ## 454      18011   5
    ## 455      18013   2
    ## 456      18015   7
    ## 457      18017   9
    ## 458      18019  12
    ## 459      18021   9
    ## 460      18023   7
    ## 461      18025   7
    ## 462      18027   6
    ## 463      18029   6
    ## 464      18031   4
    ## 465      18033   7
    ## 466      18035  12
    ## 467      18037   9
    ## 468      18039  11
    ## 469      18041   2
    ## 470      18043   4
    ## 471      18045   7
    ## 472      18047   7
    ## 473      18049   4
    ## 474      18051  10
    ## 475      18053  11
    ## 476      18055  10
    ## 477      18057  13
    ## 478      18059   6
    ## 479      18061  12
    ## 480      18063  10
    ## 481      18065  14
    ## 482      18067   4
    ## 483      18069   4
    ## 484      18071   7
    ## 485      18073   5
    ## 486      18075   6
    ## 487      18077   4
    ## 488      18079   6
    ## 489      18081   9
    ## 490      18083  11
    ## 491      18085  14
    ## 492      18087   7
    ## 493      18089  27
    ## 494      18091  11
    ## 495      18093   8
    ## 496      18095  14
    ## 497      18097  38
    ## 498      18099   7
    ## 499      18101   3
    ## 500      18103   8
    ## 501      18105  10
    ## 502      18107  11
    ## 503      18109   6
    ## 504      18111   8
    ## 505      18113   9
    ## 506      18115   1
    ## 507      18117   4
    ## 508      18119   8
    ## 509      18121   6
    ## 510      18123   9
    ## 511      18125   6
    ## 512      18127   8
    ## 513      18129   6
    ## 514      18131   5
    ## 515      18133   8
    ## 516      18135   9
    ## 517      18137   8
    ## 518      18139   8
    ## 519      18141  20
    ## 520      18143   3
    ## 521      18145   8
    ## 522      18147  12
    ## 523      18149   6
    ## 524      18151   6
    ## 525      18153   9
    ## 526      18155   5
    ## 527      18157  12
    ## 528      18159   6
    ## 529      18161   3
    ## 530      18163   9
    ## 531      18165   7
    ## 532      18167  13
    ## 533      18169   9
    ## 534      18171   4
    ## 535      18173   6
    ## 536      18175   5
    ## 537      18177  11
    ## 538      18179   9
    ## 539      18181   9
    ## 540      18183   4
    ## 541      19001   5
    ## 542      19003   4
    ## 543      19005   7
    ## 544      19007   9
    ## 545      19009   5
    ## 546      19011  15
    ## 547      19013  10
    ## 548      19015   4
    ## 549      19017   7
    ## 550      19019  11
    ## 551      19021   8
    ## 552      19023  10
    ## 553      19025   8
    ## 554      19027  11
    ## 555      19029   8
    ## 556      19031   8
    ## 557      19033  10
    ## 558      19035   8
    ## 559      19037   6
    ## 560      19039   3
    ## 561      19041   8
    ## 562      19043  15
    ## 563      19045  14
    ## 564      19047  10
    ## 565      19049  16
    ## 566      19051   4
    ## 567      19053   8
    ## 568      19055   9
    ## 569      19057   7
    ## 570      19059   7
    ## 571      19061  14
    ## 572      19063   5
    ## 573      19065  14
    ## 574      19067   7
    ## 575      19069   8
    ## 576      19071   9
    ## 577      19073   7
    ## 578      19075   8
    ## 579      19077   9
    ## 580      19079   9
    ## 581      19081   8
    ## 582      19083  10
    ## 583      19085  10
    ## 584      19087   8
    ## 585      19089   5
    ## 586      19091  11
    ## 587      19093   5
    ## 588      19095  12
    ## 589      19097  11
    ## 590      19099  10
    ## 591      19101   6
    ## 592      19103  12
    ## 593      19105   9
    ## 594      19107  13
    ## 595      19109  12
    ## 596      19111   9
    ## 597      19113  22
    ## 598      19115   7
    ## 599      19117   5
    ## 600      19119   8
    ## 601      19121   8
    ## 602      19123   9
    ## 603      19125  12
    ## 604      19127  13
    ## 605      19129   8
    ## 606      19131   8
    ## 607      19133   9
    ## 608      19135   3
    ## 609      19137   5
    ## 610      19139   9
    ## 611      19141   8
    ## 612      19143   5
    ## 613      19145   9
    ## 614      19147   8
    ## 615      19149   8
    ## 616      19151   8
    ## 617      19153  29
    ## 618      19155  16
    ## 619      19157   8
    ## 620      19159   7
    ## 621      19161   9
    ## 622      19163  19
    ## 623      19165  10
    ## 624      19167  13
    ## 625      19169  18
    ## 626      19171  13
    ## 627      19173   7
    ## 628      19175   6
    ## 629      19177  10
    ## 630      19179   7
    ## 631      19181  11
    ## 632      19183   8
    ## 633      19185   8
    ## 634      19187  14
    ## 635      19189   7
    ## 636      19191   7
    ## 637      19193  22
    ## 638      19195   7
    ## 639      19197   8
    ## 640      20001   6
    ## 641      20003   6
    ## 642      20005   5
    ## 643      20007   8
    ## 644      20009   7
    ## 645      20011   7
    ## 646      20013   7
    ## 647      20015  16
    ## 648      20017   5
    ## 649      20019   5
    ## 650      20021   8
    ## 651      20023   2
    ## 652      20025   3
    ## 653      20027   5
    ## 654      20029   6
    ## 655      20031   5
    ## 656      20033   3
    ## 657      20035   8
    ## 658      20037  13
    ## 659      20039   4
    ## 660      20041   8
    ## 661      20043   7
    ## 662      20045   8
    ## 663      20047   4
    ## 664      20049   5
    ## 665      20051   6
    ## 666      20053   5
    ## 667      20055   3
    ## 668      20057   6
    ## 669      20059   8
    ## 670      20061   2
    ## 671      20063   5
    ## 672      20065   4
    ## 673      20067   1
    ## 674      20069   5
    ## 675      20071   1
    ## 676      20073   8
    ## 677      20075   3
    ## 678      20077   7
    ## 679      20079   7
    ## 680      20081   2
    ## 681      20083   2
    ## 682      20085   9
    ## 683      20087   9
    ## 684      20089   7
    ## 685      20091  33
    ## 686      20093   2
    ## 687      20095   7
    ## 688      20097   3
    ## 689      20099   8
    ## 690      20101   2
    ## 691      20103   7
    ## 692      20105   4
    ## 693      20107   7
    ## 694      20109   3
    ## 695      20111   8
    ## 696      20113   8
    ## 697      20115  11
    ## 698      20117  11
    ## 699      20119   3
    ## 700      20121   5
    ## 701      20123   6
    ## 702      20125   9
    ## 703      20127   5
    ## 704      20129   3
    ## 705       2013   5
    ## 706      20131   9
    ## 707      20133   6
    ## 708      20135   7
    ## 709      20137   4
    ## 710      20139   9
    ## 711      20141   6
    ## 712      20143   4
    ## 713      20145   4
    ## 714      20147   7
    ## 715      20149   9
    ## 716      20151   5
    ## 717      20153   4
    ## 718      20155  13
    ## 719      20157   8
    ## 720      20159   8
    ## 721       2016   7
    ## 722      20161   8
    ## 723      20163   5
    ## 724      20165   8
    ## 725      20167   7
    ## 726      20169   6
    ## 727      20171   1
    ## 728      20173  42
    ## 729      20175   2
    ## 730      20177  24
    ## 731      20179   2
    ## 732      20181   3
    ## 733      20183   6
    ## 734      20185   4
    ## 735      20187   2
    ## 736      20189   2
    ## 737      20191  12
    ## 738      20193   5
    ## 739      20195   3
    ## 740      20197   7
    ## 741      20199   3
    ## 742       2020  16
    ## 743      20201  11
    ## 744      20203   2
    ## 745      20205   5
    ## 746      20207   4
    ## 747      20209  10
    ## 748       2050  26
    ## 749       2060   3
    ## 750       2068   5
    ## 751       2070   7
    ## 752       2090   8
    ## 753       2100   1
    ## 754      21001   4
    ## 755      21003   3
    ## 756      21005   1
    ## 757      21007   5
    ## 758      21009   6
    ## 759      21011   4
    ## 760      21013   9
    ## 761      21015   7
    ## 762      21017   2
    ## 763      21019   4
    ## 764      21021   4
    ## 765      21023   4
    ## 766      21025   5
    ## 767      21027  12
    ## 768      21029   5
    ## 769      21031   3
    ## 770      21033   2
    ## 771      21035   6
    ## 772      21037  10
    ## 773      21039   3
    ## 774      21041   3
    ## 775      21043   5
    ## 776      21045   6
    ## 777      21047   9
    ## 778      21049   1
    ## 779       2105   6
    ## 780      21051   6
    ## 781      21053   2
    ## 782      21055   2
    ## 783      21057   2
    ## 784      21059   7
    ## 785      21061   5
    ## 786      21063   2
    ## 787      21065   2
    ## 788      21067  15
    ## 789      21069   4
    ## 790      21071  32
    ## 791      21073   2
    ## 792      21075   2
    ## 793      21077   3
    ## 794      21079   1
    ## 795      21081   5
    ## 796      21083  11
    ## 797      21085   6
    ## 798      21087   3
    ## 799      21089   7
    ## 800      21091   2
    ## 801      21093  12
    ## 802      21095  26
    ## 803      21097   2
    ## 804      21099   7
    ## 805       2110   2
    ## 806      21101   5
    ## 807      21103  11
    ## 808      21105   2
    ## 809      21107  10
    ## 810      21109   5
    ## 811      21111  37
    ## 812      21113   2
    ## 813      21115  17
    ## 814      21117   8
    ## 815      21119  18
    ## 816      21121  15
    ## 817      21123   2
    ## 818      21125   6
    ## 819      21127   7
    ## 820      21129   2
    ## 821      21131  16
    ## 822      21133  24
    ## 823      21135   5
    ## 824      21137   5
    ## 825      21139   7
    ## 826      21141   5
    ## 827      21143   2
    ## 828      21145   4
    ## 829      21147   6
    ## 830      21149   5
    ## 831      21151   5
    ## 832      21153   3
    ## 833      21155   8
    ## 834      21157   4
    ## 835      21159   7
    ## 836      21161   4
    ## 837      21163   7
    ## 838      21165   4
    ## 839      21167   3
    ## 840      21169   5
    ## 841      21171   5
    ## 842      21173   3
    ## 843      21175   5
    ## 844      21177  13
    ## 845      21179   9
    ## 846      21181   2
    ## 847      21183  12
    ## 848      21185   6
    ## 849      21187   2
    ## 850      21189   1
    ## 851      21191   3
    ## 852      21193  21
    ## 853      21195  36
    ## 854      21197   3
    ## 855      21199   8
    ## 856      21201   1
    ## 857      21203   4
    ## 858      21205   2
    ## 859      21207   2
    ## 860      21209   3
    ## 861      21211   5
    ## 862      21213   1
    ## 863      21215   2
    ## 864      21217   3
    ## 865      21219   5
    ## 866       2122  14
    ## 867      21221   1
    ## 868      21223   2
    ## 869      21225   4
    ## 870      21227   9
    ## 871      21229   3
    ## 872      21231   1
    ## 873      21233   6
    ## 874      21235   5
    ## 875      21237   4
    ## 876      21239   2
    ## 877       2130   1
    ## 878       2150  17
    ## 879       2164  12
    ## 880       2170   9
    ## 881       2180  14
    ## 882       2185  11
    ## 883       2188  11
    ## 884       2195   3
    ## 885       2198   8
    ## 886      22001  10
    ## 887      22003   9
    ## 888      22005   7
    ## 889      22007   6
    ## 890      22009  12
    ## 891      22011   6
    ## 892      22013   6
    ## 893      22015   8
    ## 894      22017  23
    ## 895      22019  14
    ## 896      22021   3
    ## 897      22023   4
    ## 898      22025   4
    ## 899      22027   5
    ## 900      22029   6
    ## 901      22031   8
    ## 902      22033  22
    ## 903      22035   3
    ## 904      22037   6
    ## 905      22039   8
    ## 906      22041   5
    ## 907      22043   6
    ## 908      22045   5
    ## 909      22047   8
    ## 910      22049   4
    ## 911      22051  17
    ## 912      22053   7
    ## 913      22055  11
    ## 914      22057   9
    ## 915      22059   5
    ## 916      22061   6
    ## 917      22063   9
    ## 918      22065   2
    ## 919      22067   5
    ## 920      22069  11
    ## 921      22071  17
    ## 922      22073   9
    ## 923      22075   8
    ## 924      22077  14
    ## 925      22079  19
    ## 926      22081   2
    ## 927      22083   5
    ## 928      22085   8
    ## 929      22087   5
    ## 930      22089   9
    ## 931      22091   2
    ## 932      22093   7
    ## 933      22095   5
    ## 934      22097  13
    ## 935      22099   3
    ## 936      22101   7
    ## 937      22103  15
    ## 938      22105  15
    ## 939      22107   3
    ## 940      22109  12
    ## 941      22111   6
    ## 942      22113   7
    ## 943      22115   9
    ## 944      22117   4
    ## 945      22119  10
    ## 946      22121   4
    ## 947      22123   4
    ## 948      22125   4
    ## 949      22127   5
    ## 950       2220   1
    ## 951       2230   1
    ## 952       2240   5
    ## 953       2261   8
    ## 954       2275   2
    ## 955       2282   1
    ## 956       2290  30
    ## 957      23001  15
    ## 958      23003  38
    ## 959      23005  38
    ## 960      23007  17
    ## 961      23009  41
    ## 962      23011  28
    ## 963      23013  19
    ## 964      23015  25
    ## 965      23017  31
    ## 966      23019  46
    ## 967      23021  12
    ## 968      23023   8
    ## 969      23025  25
    ## 970      23027  18
    ## 971      23029  32
    ## 972      23031  36
    ## 973      24001  15
    ## 974      24003  35
    ## 975      24005  41
    ## 976      24009  13
    ## 977      24011   9
    ## 978      24013  10
    ## 979      24015  16
    ## 980      24017  21
    ## 981      24019  16
    ## 982      24021  27
    ## 983      24023   9
    ## 984      24025  20
    ## 985      24027  20
    ## 986      24029   9
    ## 987      24031  45
    ## 988      24033  35
    ## 989      24035  11
    ## 990      24037  25
    ## 991      24039  10
    ## 992      24041  15
    ## 993      24043  17
    ## 994      24045  16
    ## 995      24047  10
    ## 996      24510  21
    ## 997      25001  50
    ## 998      25003  33
    ## 999      25005  35
    ## 1000     25007   6
    ## 1001     25009  43
    ## 1002     25011  28
    ## 1003     25013  39
    ## 1004     25015  25
    ## 1005     25017  81
    ## 1006     25019   2
    ## 1007     25021  40
    ## 1008     25023  33
    ## 1009     25025  32
    ## 1010     25027  86
    ## 1011     26001   9
    ## 1012     26003  10
    ## 1013     26005  14
    ## 1014     26007   5
    ## 1015     26009  10
    ## 1016     26011   7
    ## 1017     26013   5
    ## 1018     26015   8
    ## 1019     26017   9
    ## 1020     26019   7
    ## 1021     26021  23
    ## 1022     26023   6
    ## 1023     26025  12
    ## 1024     26027   7
    ## 1025     26029   6
    ## 1026     26031   6
    ## 1027     26033  15
    ## 1028     26035   5
    ## 1029     26037   9
    ## 1030     26039   2
    ## 1031     26041  10
    ## 1032     26043  11
    ## 1033     26045  11
    ## 1034     26047  10
    ## 1035     26049  24
    ## 1036     26051   3
    ## 1037     26053   6
    ## 1038     26055   7
    ## 1039     26057  13
    ## 1040     26059  13
    ## 1041     26061  17
    ## 1042     26063  14
    ## 1043     26065  18
    ## 1044     26067  12
    ## 1045     26069   8
    ## 1046     26071   6
    ## 1047     26073   6
    ## 1048     26075  17
    ## 1049     26077  18
    ## 1050     26079   4
    ## 1051     26081  28
    ## 1052     26083   4
    ## 1053     26085   5
    ## 1054     26087  11
    ## 1055     26089   9
    ## 1056     26091  18
    ## 1057     26093  10
    ## 1058     26095   2
    ## 1059     26097  10
    ## 1060     26099  36
    ## 1061     26101  10
    ## 1062     26103  12
    ## 1063     26105   7
    ## 1064     26107   9
    ## 1065     26109  12
    ## 1066     26111   5
    ## 1067     26113   4
    ## 1068     26115  16
    ## 1069     26117  16
    ## 1070     26119   3
    ## 1071     26121  13
    ## 1072     26123   6
    ## 1073     26125  68
    ## 1074     26127   8
    ## 1075     26129   4
    ## 1076     26131   9
    ## 1077     26133   7
    ## 1078     26135   4
    ## 1079     26137   3
    ## 1080     26139  13
    ## 1081     26141   6
    ## 1082     26143   6
    ## 1083     26145  19
    ## 1084     26147  21
    ## 1085     26149  10
    ## 1086     26151  16
    ## 1087     26153   5
    ## 1088     26155  12
    ## 1089     26157  14
    ## 1090     26159  13
    ## 1091     26161  15
    ## 1092     26163  66
    ## 1093     26165   6
    ## 1094     27001   8
    ## 1095     27003  12
    ## 1096     27005  12
    ## 1097     27007  13
    ## 1098     27009   4
    ## 1099     27011   7
    ## 1100     27013  11
    ## 1101     27015   5
    ## 1102     27017  11
    ## 1103     27019  12
    ## 1104     27021  12
    ## 1105     27023   5
    ## 1106     27025  10
    ## 1107     27027  11
    ## 1108     27029   5
    ## 1109     27031   6
    ## 1110     27033   6
    ## 1111     27035  14
    ## 1112     27037  19
    ## 1113     27039   6
    ## 1114     27041  10
    ## 1115     27043  11
    ## 1116     27045  12
    ## 1117     27047  12
    ## 1118     27049  10
    ## 1119     27051   7
    ## 1120     27053  65
    ## 1121     27055   7
    ## 1122     27057   6
    ## 1123     27059   6
    ## 1124     27061  22
    ## 1125     27063   5
    ## 1126     27065   3
    ## 1127     27067  11
    ## 1128     27069   9
    ## 1129     27071  10
    ## 1130     27073   5
    ## 1131     27075   6
    ## 1132     27077   4
    ## 1133     27079   8
    ## 1134     27081   5
    ## 1135     27083  10
    ## 1136     27085   8
    ## 1137     27087   5
    ## 1138     27089  11
    ## 1139     27091  10
    ## 1140     27093   6
    ## 1141     27095   8
    ## 1142     27097  10
    ## 1143     27099  14
    ## 1144     27101   8
    ## 1145     27103   5
    ## 1146     27105  11
    ## 1147     27107   9
    ## 1148     27109   9
    ## 1149     27113   3
    ## 1150     27115  11
    ## 1151     27117   8
    ## 1152     27119  15
    ## 1153     27121   5
    ## 1154     27123  19
    ## 1155     27125   4
    ## 1156     27127  14
    ## 1157     27129  10
    ## 1158     27131   8
    ## 1159     27133   8
    ## 1160     27135   8
    ## 1161     27137  45
    ## 1162     27139   8
    ## 1163     27141   6
    ## 1164     27143   7
    ## 1165     27145  27
    ## 1166     27147   5
    ## 1167     27149   5
    ## 1168     27151   7
    ## 1169     27153  30
    ## 1170     27155   4
    ## 1171     27157   9
    ## 1172     27159   4
    ## 1173     27161   4
    ## 1174     27163  24
    ## 1175     27167   7
    ## 1176     27169   8
    ## 1177     27171  14
    ## 1178     27173   7
    ## 1179     28001   1
    ## 1180     28003   3
    ## 1181     28005   3
    ## 1182     28007   5
    ## 1183     28009   4
    ## 1184     28011  14
    ## 1185     28013   6
    ## 1186     28015   5
    ## 1187     28017   4
    ## 1188     28019   3
    ## 1189     28021   4
    ## 1190     28023   4
    ## 1191     28025   4
    ## 1192     28027   9
    ## 1193     28029   4
    ## 1194     28031   3
    ## 1195     28033   8
    ## 1196     28035   4
    ## 1197     28037   4
    ## 1198     28039   1
    ## 1199     28041   3
    ## 1200     28043   3
    ## 1201     28045   5
    ## 1202     28047  11
    ## 1203     28049  18
    ## 1204     28051   6
    ## 1205     28053   5
    ## 1206     28055   4
    ## 1207     28057   5
    ## 1208     28059   7
    ## 1209     28061   8
    ## 1210     28063   2
    ## 1211     28065   4
    ## 1212     28067   7
    ## 1213     28069   4
    ## 1214     28071   5
    ## 1215     28073   4
    ## 1216     28075  10
    ## 1217     28077   4
    ## 1218     28079   3
    ## 1219     28081   9
    ## 1220     28083   8
    ## 1221     28085   3
    ## 1222     28087   7
    ## 1223     28089   6
    ## 1224     28091   4
    ## 1225     28093   5
    ## 1226     28095   7
    ## 1227     28097   3
    ## 1228     28099   2
    ## 1229     28101   7
    ## 1230     28103   3
    ## 1231     28105   3
    ## 1232     28107   6
    ## 1233     28109   3
    ## 1234     28111   3
    ## 1235     28113   5
    ## 1236     28115   5
    ## 1237     28117   3
    ## 1238     28119   6
    ## 1239     28121   8
    ## 1240     28123   4
    ## 1241     28125   5
    ## 1242     28127   6
    ## 1243     28129   4
    ## 1244     28131   3
    ## 1245     28133  10
    ## 1246     28135  10
    ## 1247     28137   3
    ## 1248     28139   6
    ## 1249     28141   5
    ## 1250     28143   3
    ## 1251     28145   4
    ## 1252     28147   2
    ## 1253     28149   3
    ## 1254     28151   9
    ## 1255     28153   3
    ## 1256     28155   7
    ## 1257     28157   3
    ## 1258     28159   2
    ## 1259     28161   4
    ## 1260     28163   6
    ## 1261     29001   5
    ## 1262     29003   8
    ## 1263     29005   5
    ## 1264     29007   8
    ## 1265     29009  11
    ## 1266     29011   4
    ## 1267     29013   8
    ## 1268     29015   5
    ## 1269     29017   8
    ## 1270     29019  11
    ## 1271     29021  11
    ## 1272     29023   6
    ## 1273     29025   7
    ## 1274     29027  10
    ## 1275     29029  10
    ## 1276     29031  12
    ## 1277     29033   7
    ## 1278     29035   4
    ## 1279     29037  13
    ## 1280     29039   3
    ## 1281     29041   8
    ## 1282     29043  12
    ## 1283     29045   6
    ## 1284     29047  18
    ## 1285     29049   6
    ## 1286     29051   7
    ## 1287     29053   7
    ## 1288     29055   8
    ## 1289     29057   6
    ## 1290     29059   7
    ## 1291     29061   8
    ## 1292     29063   7
    ## 1293     29065   4
    ## 1294     29067   4
    ## 1295     29069  12
    ## 1296     29071  20
    ## 1297     29073   6
    ## 1298     29075   6
    ## 1299     29077  15
    ## 1300     29079   4
    ## 1301     29081   9
    ## 1302     29083   7
    ## 1303     29085   8
    ## 1304     29087   5
    ## 1305     29089   5
    ## 1306     29091   7
    ## 1307     29093  10
    ## 1308     29095  55
    ## 1309     29097  16
    ## 1310     29099  15
    ## 1311     29101   8
    ## 1312     29103   7
    ## 1313     29105   6
    ## 1314     29107  12
    ## 1315     29109  11
    ## 1316     29111   8
    ## 1317     29113  10
    ## 1318     29115   9
    ## 1319     29117   7
    ## 1320     29119   9
    ## 1321     29121  10
    ## 1322     29123   2
    ## 1323     29125   5
    ## 1324     29127   5
    ## 1325     29129   2
    ## 1326     29131   9
    ## 1327     29133   5
    ## 1328     29135   5
    ## 1329     29137   6
    ## 1330     29139   8
    ## 1331     29141   8
    ## 1332     29143  13
    ## 1333     29145   7
    ## 1334     29147  15
    ## 1335     29149   5
    ## 1336     29151   8
    ## 1337     29153  13
    ## 1338     29155   8
    ## 1339     29157   5
    ## 1340     29159   7
    ## 1341     29161   7
    ## 1342     29163   8
    ## 1343     29165  13
    ## 1344     29167  10
    ## 1345     29169   8
    ## 1346     29171   5
    ## 1347     29173   4
    ## 1348     29175   8
    ## 1349     29177   7
    ## 1350     29179   7
    ## 1351     29181   5
    ## 1352     29183  13
    ## 1353     29185   5
    ## 1354     29186   3
    ## 1355     29187   8
    ## 1356     29189  43
    ## 1357     29195  10
    ## 1358     29197   5
    ## 1359     29199   4
    ## 1360     29201  11
    ## 1361     29203   3
    ## 1362     29205   8
    ## 1363     29207   9
    ## 1364     29209   8
    ## 1365     29211   8
    ## 1366     29213  14
    ## 1367     29215  15
    ## 1368     29217  11
    ## 1369     29219   4
    ## 1370     29221  10
    ## 1371     29223  10
    ## 1372     29225   5
    ## 1373     29227   5
    ## 1374     29229   7
    ## 1375     29510  18
    ## 1376     30001   8
    ## 1377     30003  10
    ## 1378     30005   7
    ## 1379     30007   3
    ## 1380     30009  10
    ## 1381     30011   3
    ## 1382     30013  15
    ## 1383     30015   7
    ## 1384     30017   3
    ## 1385     30019   4
    ## 1386     30021   4
    ## 1387     30023   2
    ## 1388     30025   3
    ## 1389     30027   9
    ## 1390     30029  15
    ## 1391     30031   9
    ## 1392     30033   6
    ## 1393     30035   4
    ## 1394     30037   2
    ## 1395     30039   3
    ## 1396     30041   7
    ## 1397     30043   5
    ## 1398     30045   6
    ## 1399     30047  12
    ## 1400     30049   9
    ## 1401     30051   5
    ## 1402     30053   7
    ## 1403     30055   3
    ## 1404     30057  12
    ## 1405     30059   3
    ## 1406     30061   6
    ## 1407     30063  13
    ## 1408     30065   3
    ## 1409     30067   9
    ## 1410     30069   1
    ## 1411     30071   6
    ## 1412     30073   5
    ## 1413     30075   5
    ## 1414     30077   7
    ## 1415     30079   2
    ## 1416     30081   9
    ## 1417     30083   5
    ## 1418     30085   6
    ## 1419     30087   8
    ## 1420     30089   9
    ## 1421     30091  10
    ## 1422     30093   6
    ## 1423     30095   7
    ## 1424     30097   4
    ## 1425     30099   6
    ## 1426     30101   6
    ## 1427     30103   3
    ## 1428     30105  10
    ## 1429     30107   4
    ## 1430     30109   1
    ## 1431     30111  14
    ## 1432     31001   6
    ## 1433     31003   7
    ## 1434     31005   1
    ## 1435     31007   1
    ## 1436     31009   3
    ## 1437     31011   5
    ## 1438     31013   2
    ## 1439     31015   5
    ## 1440     31017   3
    ## 1441     31019  12
    ## 1442     31021   5
    ## 1443     31023  10
    ## 1444     31025  15
    ## 1445     31027   9
    ## 1446     31029   4
    ## 1447     31031   9
    ## 1448     31033   5
    ## 1449     31035  11
    ## 1450     31037   5
    ## 1451     31039   4
    ## 1452     31041  11
    ## 1453     31043   5
    ## 1454     31045   4
    ## 1455     31047   8
    ## 1456     31049   2
    ## 1457     31051   9
    ## 1458     31053  10
    ## 1459     31055  33
    ## 1460     31057   4
    ## 1461     31059   8
    ## 1462     31061   7
    ## 1463     31063   5
    ## 1464     31065   8
    ## 1465     31067  12
    ## 1466     31069   3
    ## 1467     31071   1
    ## 1468     31073   2
    ## 1469     31075   3
    ## 1470     31077   4
    ## 1471     31079   6
    ## 1472     31081   6
    ## 1473     31083   5
    ## 1474     31085   1
    ## 1475     31087   4
    ## 1476     31089   9
    ## 1477     31091   1
    ## 1478     31093   6
    ## 1479     31095   7
    ## 1480     31097   5
    ## 1481     31099   4
    ## 1482     31101   5
    ## 1483     31103   2
    ## 1484     31105   3
    ## 1485     31107   8
    ## 1486     31109  36
    ## 1487     31111   8
    ## 1488     31113   1
    ## 1489     31115   1
    ## 1490     31117   1
    ## 1491     31119   6
    ## 1492     31121   6
    ## 1493     31123   4
    ## 1494     31125   3
    ## 1495     31127   7
    ## 1496     31129   6
    ## 1497     31131  10
    ## 1498     31133   6
    ## 1499     31135   4
    ## 1500     31137   5
    ## 1501     31139   4
    ## 1502     31141   7
    ## 1503     31143   4
    ## 1504     31145   5
    ## 1505     31147   8
    ## 1506     31149   2
    ## 1507     31151   8
    ## 1508     31153  12
    ## 1509     31155  14
    ## 1510     31157   8
    ## 1511     31159   9
    ## 1512     31161   7
    ## 1513     31163   5
    ## 1514     31165   1
    ## 1515     31167   2
    ## 1516     31169  11
    ## 1517     31171   3
    ## 1518     31173   6
    ## 1519     31175   4
    ## 1520     31177   6
    ## 1521     31179   4
    ## 1522     31181   5
    ## 1523     31183   2
    ## 1524     31185   7
    ## 1525     32001   1
    ## 1526     32003  73
    ## 1527     32005   9
    ## 1528     32007  14
    ## 1529     32009   3
    ## 1530     32011   2
    ## 1531     32013   6
    ## 1532     32015   2
    ## 1533     32017   5
    ## 1534     32019   6
    ## 1535     32021   4
    ## 1536     32023  10
    ## 1537     32027   2
    ## 1538     32029   1
    ## 1539     32031  25
    ## 1540     32033   5
    ## 1541     32510   4
    ## 1542     33001  13
    ## 1543     33003  28
    ## 1544     33005  25
    ## 1545     33007  15
    ## 1546     33009  36
    ## 1547     33011  34
    ## 1548     33013  28
    ## 1549     33015  36
    ## 1550     33017  16
    ## 1551     33019  16
    ## 1552     34001  26
    ## 1553     34003  66
    ## 1554     34005  33
    ## 1555     34007  34
    ## 1556     34009  15
    ## 1557     34011  17
    ## 1558     34013  31
    ## 1559     34015  26
    ## 1560     34017  16
    ## 1561     34019  20
    ## 1562     34021  21
    ## 1563     34023  35
    ## 1564     34025  50
    ## 1565     34027  49
    ## 1566     34029  29
    ## 1567     34031  27
    ## 1568     34033  10
    ## 1569     34035  25
    ## 1570     34037  19
    ## 1571     34039  26
    ## 1572     34041  14
    ## 1573     35001  22
    ## 1574     35003   7
    ## 1575     35005   5
    ## 1576     35006  14
    ## 1577     35007   8
    ## 1578     35009   6
    ## 1579     35011   3
    ## 1580     35013  25
    ## 1581     35015   7
    ## 1582     35017  16
    ## 1583     35019   5
    ## 1584     35021   3
    ## 1585     35023   4
    ## 1586     35025   9
    ## 1587     35027  15
    ## 1588     35028   1
    ## 1589     35029   2
    ## 1590     35031  19
    ## 1591     35033  12
    ## 1592     35035  17
    ## 1593     35037   7
    ## 1594     35039  29
    ## 1595     35041   8
    ## 1596     35043  18
    ## 1597     35045  17
    ## 1598     35047  13
    ## 1599     35049  12
    ## 1600     35051   9
    ## 1601     35053   9
    ## 1602     35055  19
    ## 1603     35057   7
    ## 1604     35059   8
    ## 1605     35061   5
    ## 1606     36001  36
    ## 1607     36003  25
    ## 1608     36005  25
    ## 1609     36007  22
    ## 1610     36009  28
    ## 1611     36011  18
    ## 1612     36013  33
    ## 1613     36015  15
    ## 1614     36017  18
    ## 1615     36019  25
    ## 1616     36021  30
    ## 1617     36023  10
    ## 1618     36025  35
    ## 1619     36027  34
    ## 1620     36029  67
    ## 1621     36031  30
    ## 1622     36033  20
    ## 1623     36035   7
    ## 1624     36037  13
    ## 1625     36039  36
    ## 1626     36041  11
    ## 1627     36043  17
    ## 1628     36045  37
    ## 1629     36047  37
    ## 1630     36049  15
    ## 1631     36051  20
    ## 1632     36053  25
    ## 1633     36055  42
    ## 1634     36057  13
    ## 1635     36059  69
    ## 1636     36061  46
    ## 1637     36063  20
    ## 1638     36065  48
    ## 1639     36067  42
    ## 1640     36069  16
    ## 1641     36071  45
    ## 1642     36073   8
    ## 1643     36075  22
    ## 1644     36077  28
    ## 1645     36079   8
    ## 1646     36081  61
    ## 1647     36083  27
    ## 1648     36085  12
    ## 1649     36087  25
    ## 1650     36089  42
    ## 1651     36091  21
    ## 1652     36093  13
    ## 1653     36095  18
    ## 1654     36097  10
    ## 1655     36099   7
    ## 1656     36101  28
    ## 1657     36103 107
    ## 1658     36105  53
    ## 1659     36107  13
    ## 1660     36109  12
    ## 1661     36111  56
    ## 1662     36113  20
    ## 1663     36115  20
    ## 1664     36117  16
    ## 1665     36119  73
    ## 1666     36121  18
    ## 1667     36123   9
    ## 1668     37001   9
    ## 1669     37003   3
    ## 1670     37005   6
    ## 1671     37007   7
    ## 1672     37009  11
    ## 1673     37011   7
    ## 1674     37013   9
    ## 1675     37015   7
    ## 1676     37017   8
    ## 1677     37019  12
    ## 1678     37021  15
    ## 1679     37023   8
    ## 1680     37025   7
    ## 1681     37027   5
    ## 1682     37029   3
    ## 1683     37031  17
    ## 1684     37033   7
    ## 1685     37035   9
    ## 1686     37037   7
    ## 1687     37039   3
    ## 1688     37041   2
    ## 1689     37043   3
    ## 1690     37045   9
    ## 1691     37047  14
    ## 1692     37049   9
    ## 1693     37051  16
    ## 1694     37053  15
    ## 1695     37055  14
    ## 1696     37057   5
    ## 1697     37059   3
    ## 1698     37061  12
    ## 1699     37063   9
    ## 1700     37065   6
    ## 1701     37067  17
    ## 1702     37069   4
    ## 1703     37071  14
    ## 1704     37073   6
    ## 1705     37075   3
    ## 1706     37077   6
    ## 1707     37079   4
    ## 1708     37081  22
    ## 1709     37083   8
    ## 1710     37085   9
    ## 1711     37087   6
    ## 1712     37089  11
    ## 1713     37091   7
    ## 1714     37093   1
    ## 1715     37095   5
    ## 1716     37097   8
    ## 1717     37099   8
    ## 1718     37101  10
    ## 1719     37103   2
    ## 1720     37105   2
    ## 1721     37107   4
    ## 1722     37109   5
    ## 1723     37111   4
    ## 1724     37113   5
    ## 1725     37115   3
    ## 1726     37117   8
    ## 1727     37119  29
    ## 1728     37121   2
    ## 1729     37123   5
    ## 1730     37125  11
    ## 1731     37127  10
    ## 1732     37129  10
    ## 1733     37131  11
    ## 1734     37133  12
    ## 1735     37135   7
    ## 1736     37137   9
    ## 1737     37139   1
    ## 1738     37141   6
    ## 1739     37143   3
    ## 1740     37145   6
    ## 1741     37147  12
    ## 1742     37149   4
    ## 1743     37151  12
    ## 1744     37153   6
    ## 1745     37155  13
    ## 1746     37157   7
    ## 1747     37159  13
    ## 1748     37161  11
    ## 1749     37163  10
    ## 1750     37165   5
    ## 1751     37167   9
    ## 1752     37169   9
    ## 1753     37171   9
    ## 1754     37173   2
    ## 1755     37175   8
    ## 1756     37177   1
    ## 1757     37179   8
    ## 1758     37181   4
    ## 1759     37183  32
    ## 1760     37185   4
    ## 1761     37187   3
    ## 1762     37189   7
    ## 1763     37191   8
    ## 1764     37193  12
    ## 1765     37195   8
    ## 1766     37197   5
    ## 1767     37199   2
    ## 1768     38001   2
    ## 1769     38003  12
    ## 1770     38005  11
    ## 1771     38007   2
    ## 1772     38009   9
    ## 1773     38011   3
    ## 1774     38013   6
    ## 1775     38015  10
    ## 1776     38017  24
    ## 1777     38019  10
    ## 1778     38021   3
    ## 1779     38023   4
    ## 1780     38025   5
    ## 1781     38027   2
    ## 1782     38029   6
    ## 1783     38031   4
    ## 1784     38033   3
    ## 1785     38035  16
    ## 1786     38037   5
    ## 1787     38039   5
    ## 1788     38041   3
    ## 1789     38043   6
    ## 1790     38045   8
    ## 1791     38047   3
    ## 1792     38049  12
    ## 1793     38051   4
    ## 1794     38053   7
    ## 1795     38055  13
    ## 1796     38057   5
    ## 1797     38059   8
    ## 1798     38061   7
    ## 1799     38063   8
    ## 1800     38065   1
    ## 1801     38067  11
    ## 1802     38069   2
    ## 1803     38071  10
    ## 1804     38073   4
    ## 1805     38075   4
    ## 1806     38077  14
    ## 1807     38079   6
    ## 1808     38081   8
    ## 1809     38083   4
    ## 1810     38085   3
    ## 1811     38087   2
    ## 1812     38089   7
    ## 1813     38091   4
    ## 1814     38093  13
    ## 1815     38095   6
    ## 1816     38097  10
    ## 1817     38099  11
    ## 1818     38101  16
    ## 1819     38103   7
    ## 1820     38105  10
    ## 1821     39001   8
    ## 1822     39003  13
    ## 1823     39005   9
    ## 1824     39007  14
    ## 1825     39009  15
    ## 1826     39011  10
    ## 1827     39013  22
    ## 1828     39015  10
    ## 1829     39017  13
    ## 1830     39019   7
    ## 1831     39021   9
    ## 1832     39023  14
    ## 1833     39025  16
    ## 1834     39027   9
    ## 1835     39029  18
    ## 1836     39031   8
    ## 1837     39033   8
    ## 1838     39035  52
    ## 1839     39037  16
    ## 1840     39039   6
    ## 1841     39041  11
    ## 1842     39043   8
    ## 1843     39045  13
    ## 1844     39047   4
    ## 1845     39049  43
    ## 1846     39051   8
    ## 1847     39053   8
    ## 1848     39055  11
    ## 1849     39057  15
    ## 1850     39059  14
    ## 1851     39061  52
    ## 1852     39063  12
    ## 1853     39065   9
    ## 1854     39067   8
    ## 1855     39069   9
    ## 1856     39071   7
    ## 1857     39073   8
    ## 1858     39075  13
    ## 1859     39077  10
    ## 1860     39079   5
    ## 1861     39081  21
    ## 1862     39083   8
    ## 1863     39085   8
    ## 1864     39087   9
    ## 1865     39089  15
    ## 1866     39091  14
    ## 1867     39093  15
    ## 1868     39095  26
    ## 1869     39097   7
    ## 1870     39099  26
    ## 1871     39101   8
    ## 1872     39103  13
    ## 1873     39105  10
    ## 1874     39107  10
    ## 1875     39109  11
    ## 1876     39111  10
    ## 1877     39113  33
    ## 1878     39115   4
    ## 1879     39117   6
    ## 1880     39119  16
    ## 1881     39121   5
    ## 1882     39123  14
    ## 1883     39125   9
    ## 1884     39127  11
    ## 1885     39129   8
    ## 1886     39131   5
    ## 1887     39133  15
    ## 1888     39135  11
    ## 1889     39137  10
    ## 1890     39139  12
    ## 1891     39141  10
    ## 1892     39143   9
    ## 1893     39145  13
    ## 1894     39147  13
    ## 1895     39149  11
    ## 1896     39151  33
    ## 1897     39153  32
    ## 1898     39155  24
    ## 1899     39157  17
    ## 1900     39159   6
    ## 1901     39161   9
    ## 1902     39163   6
    ## 1903     39165  12
    ## 1904     39167  18
    ## 1905     39169  15
    ## 1906     39171  10
    ## 1907     39173  26
    ## 1908     39175   8
    ## 1909     40001   5
    ## 1910     40003   8
    ## 1911     40005   6
    ## 1912     40007   5
    ## 1913     40009   4
    ## 1914      4001  27
    ## 1915     40011   8
    ## 1916     40013  11
    ## 1917     40015  12
    ## 1918     40017   7
    ## 1919     40019   9
    ## 1920     40021   6
    ## 1921     40023   8
    ## 1922     40025   4
    ## 1923     40027  12
    ## 1924     40029   5
    ## 1925      4003  22
    ## 1926     40031  13
    ## 1927     40033   4
    ## 1928     40035   5
    ## 1929     40037  13
    ## 1930     40039   6
    ## 1931     40041   9
    ## 1932     40043   7
    ## 1933     40045   4
    ## 1934     40047  15
    ## 1935     40049   7
    ## 1936      4005  23
    ## 1937     40051  10
    ## 1938     40053   7
    ## 1939     40055   3
    ## 1940     40057   3
    ## 1941     40059   4
    ## 1942     40061   6
    ## 1943     40063   7
    ## 1944     40065   8
    ## 1945     40067   5
    ## 1946     40069  10
    ## 1947      4007   9
    ## 1948     40071   8
    ## 1949     40073   7
    ## 1950     40075   7
    ## 1951     40077   2
    ## 1952     40079  17
    ## 1953     40081  10
    ## 1954     40083   8
    ## 1955     40085   5
    ## 1956     40087   6
    ## 1957     40089  14
    ## 1958      4009   9
    ## 1959     40091   6
    ## 1960     40093   7
    ## 1961     40095   3
    ## 1962     40097   9
    ## 1963     40099   4
    ## 1964     40101  12
    ## 1965     40103   6
    ## 1966     40105   5
    ## 1967     40107   5
    ## 1968     40109  52
    ## 1969      4011   4
    ## 1970     40111   8
    ## 1971     40113  11
    ## 1972     40115   7
    ## 1973     40117   7
    ## 1974     40119   8
    ## 1975      4012   8
    ## 1976     40121  13
    ## 1977     40123   7
    ## 1978     40125   9
    ## 1979     40127  10
    ## 1980     40129   6
    ## 1981      4013 131
    ## 1982     40131   7
    ## 1983     40133   6
    ## 1984     40135   8
    ## 1985     40137   7
    ## 1986     40139   7
    ## 1987     40141   7
    ## 1988     40143  36
    ## 1989     40145   6
    ## 1990     40147   7
    ## 1991     40149  10
    ## 1992      4015  23
    ## 1993     40151   5
    ## 1994     40153   5
    ## 1995      4017  27
    ## 1996      4019  45
    ## 1997      4021  26
    ## 1998      4023   7
    ## 1999      4025  28
    ## 2000      4027  10
    ## 2001     41001  11
    ## 2002     41003   7
    ## 2003     41005  24
    ## 2004     41007   7
    ## 2005     41009   8
    ## 2006     41011   8
    ## 2007     41013   4
    ## 2008     41015   6
    ## 2009     41017   7
    ## 2010     41019  24
    ## 2011     41021   2
    ## 2012     41023  10
    ## 2013     41025   9
    ## 2014     41027   3
    ## 2015     41029  15
    ## 2016     41031   6
    ## 2017     41033  10
    ## 2018     41035  17
    ## 2019     41037   8
    ## 2020     41039  34
    ## 2021     41041  16
    ## 2022     41043  14
    ## 2023     41045  11
    ## 2024     41047  24
    ## 2025     41049   5
    ## 2026     41051  32
    ## 2027     41053   7
    ## 2028     41055   5
    ## 2029     41057  13
    ## 2030     41059  13
    ## 2031     41061   7
    ## 2032     41063   5
    ## 2033     41065   7
    ## 2034     41067  21
    ## 2035     41069   3
    ## 2036     41071  10
    ## 2037     42001  13
    ## 2038     42003  97
    ## 2039     42005  22
    ## 2040     42007  20
    ## 2041     42009  24
    ## 2042     42011  49
    ## 2043     42013  14
    ## 2044     42015  21
    ## 2045     42017  43
    ## 2046     42019  31
    ## 2047     42021  46
    ## 2048     42023   3
    ## 2049     42025  15
    ## 2050     42027  27
    ## 2051     42029  36
    ## 2052     42031  23
    ## 2053     42033  43
    ## 2054     42035  14
    ## 2055     42037  11
    ## 2056     42039  20
    ## 2057     42041  19
    ## 2058     42043  24
    ## 2059     42045  38
    ## 2060     42047  12
    ## 2061     42049  30
    ## 2062     42051  55
    ## 2063     42053   6
    ## 2064     42055  30
    ## 2065     42057  11
    ## 2066     42059  23
    ## 2067     42061  25
    ## 2068     42063  44
    ## 2069     42065  24
    ## 2070     42067  10
    ## 2071     42069  24
    ## 2072     42071  49
    ## 2073     42073  16
    ## 2074     42075  16
    ## 2075     42077  28
    ## 2076     42079  40
    ## 2077     42081  18
    ## 2078     42083  19
    ## 2079     42085  19
    ## 2080     42087  11
    ## 2081     42089  32
    ## 2082     42091  57
    ## 2083     42093   2
    ## 2084     42095  22
    ## 2085     42097  24
    ## 2086     42099  14
    ## 2087     42101  46
    ## 2088     42103  14
    ## 2089     42105  10
    ## 2090     42107  55
    ## 2091     42109  10
    ## 2092     42111  34
    ## 2093     42113   9
    ## 2094     42115  23
    ## 2095     42117  21
    ## 2096     42119  13
    ## 2097     42121  14
    ## 2098     42123  16
    ## 2099     42125  53
    ## 2100     42127  23
    ## 2101     42129  78
    ## 2102     42131   9
    ## 2103     42133  39
    ## 2104     44001   3
    ## 2105     44003   8
    ## 2106     44005   8
    ## 2107     44007  38
    ## 2108     44009  20
    ## 2109     45001   5
    ## 2110     45003  18
    ## 2111     45005   4
    ## 2112     45007  12
    ## 2113     45009   4
    ## 2114     45011   4
    ## 2115     45013  14
    ## 2116     45015  12
    ## 2117     45017   2
    ## 2118     45019  25
    ## 2119     45021   3
    ## 2120     45023   6
    ## 2121     45025   8
    ## 2122     45027   5
    ## 2123     45029  10
    ## 2124     45031   6
    ## 2125     45033   7
    ## 2126     45035   9
    ## 2127     45037   5
    ## 2128     45039   4
    ## 2129     45041  11
    ## 2130     45043   3
    ## 2131     45045  21
    ## 2132     45047   6
    ## 2133     45049  11
    ## 2134     45051  16
    ## 2135     45053   4
    ## 2136     45055   7
    ## 2137     45057   4
    ## 2138     45059   9
    ## 2139     45061   3
    ## 2140     45063  14
    ## 2141     45065   6
    ## 2142     45067   4
    ## 2143     45069   6
    ## 2144     45071   8
    ## 2145     45073  11
    ## 2146     45075  17
    ## 2147     45077  10
    ## 2148     45079  18
    ## 2149     45081   2
    ## 2150     45083  32
    ## 2151     45085  11
    ## 2152     45087   5
    ## 2153     45089   7
    ## 2154     45091  12
    ## 2155     46003   3
    ## 2156     46005   8
    ## 2157     46007   3
    ## 2158     46009   5
    ## 2159     46011   7
    ## 2160     46013  14
    ## 2161     46015   3
    ## 2162     46017   2
    ## 2163     46019   4
    ## 2164     46021   3
    ## 2165     46023   7
    ## 2166     46025   6
    ## 2167     46027   3
    ## 2168     46029   6
    ## 2169     46031   9
    ## 2170     46033   5
    ## 2171     46035   3
    ## 2172     46037   7
    ## 2173     46039   6
    ## 2174     46041   7
    ## 2175     46043   5
    ## 2176     46045   4
    ## 2177     46047   5
    ## 2178     46049   5
    ## 2179     46051   8
    ## 2180     46053   7
    ## 2181     46055   3
    ## 2182     46057   6
    ## 2183     46059   4
    ## 2184     46061   3
    ## 2185     46063   6
    ## 2186     46065   3
    ## 2187     46067   6
    ## 2188     46069   3
    ## 2189     46071   5
    ## 2190     46073   3
    ## 2191     46075   3
    ## 2192     46077   7
    ## 2193     46079   7
    ## 2194     46081   7
    ## 2195     46083   8
    ## 2196     46085   6
    ## 2197     46087   5
    ## 2198     46089   4
    ## 2199     46091   6
    ## 2200     46093   9
    ## 2201     46095   3
    ## 2202     46097   4
    ## 2203     46099  19
    ## 2204     46101  11
    ## 2205     46103  13
    ## 2206     46105   5
    ## 2207     46107   4
    ## 2208     46109   9
    ## 2209     46111   3
    ## 2210     46115  10
    ## 2211     46117   2
    ## 2212     46119   2
    ## 2213     46121   5
    ## 2214     46123   5
    ## 2215     46125   8
    ## 2216     46127   5
    ## 2217     46129   5
    ## 2218     46135   7
    ## 2219     46137   3
    ## 2220     47001   7
    ## 2221     47003   4
    ## 2222     47005   4
    ## 2223     47007   1
    ## 2224     47009  10
    ## 2225     47011   6
    ## 2226     47013   6
    ## 2227     47015   4
    ## 2228     47017  12
    ## 2229     47019   5
    ## 2230     47021   5
    ## 2231     47023   4
    ## 2232     47025   8
    ## 2233     47027   2
    ## 2234     47029   6
    ## 2235     47031   5
    ## 2236     47033   6
    ## 2237     47035   6
    ## 2238     47037  29
    ## 2239     47039   4
    ## 2240     47041   4
    ## 2241     47043   7
    ## 2242     47045   7
    ## 2243     47047   8
    ## 2244     47049   4
    ## 2245     47051   8
    ## 2246     47053   8
    ## 2247     47055   7
    ## 2248     47057   6
    ## 2249     47059   7
    ## 2250     47061   8
    ## 2251     47063   5
    ## 2252     47065  26
    ## 2253     47067   2
    ## 2254     47069   9
    ## 2255     47071   7
    ## 2256     47073   7
    ## 2257     47075   2
    ## 2258     47077   7
    ## 2259     47079   7
    ## 2260     47081   6
    ## 2261     47083   3
    ## 2262     47085   4
    ## 2263     47087   4
    ## 2264     47089   5
    ## 2265     47091   5
    ## 2266     47093  21
    ## 2267     47095   3
    ## 2268     47097   4
    ## 2269     47099   8
    ## 2270     47101   1
    ## 2271     47103   9
    ## 2272     47105   5
    ## 2273     47107   6
    ## 2274     47109   9
    ## 2275     47111   2
    ## 2276     47113   8
    ## 2277     47115   6
    ## 2278     47117   4
    ## 2279     47119   6
    ## 2280     47121   2
    ## 2281     47123   4
    ## 2282     47125   8
    ## 2283     47127   1
    ## 2284     47129   8
    ## 2285     47131   7
    ## 2286     47133   9
    ## 2287     47135   2
    ## 2288     47137   2
    ## 2289     47139   9
    ## 2290     47141   7
    ## 2291     47143   5
    ## 2292     47145   4
    ## 2293     47147   6
    ## 2294     47149  12
    ## 2295     47151   7
    ## 2296     47153   1
    ## 2297     47155   6
    ## 2298     47157  34
    ## 2299     47159  10
    ## 2300     47161   5
    ## 2301     47163   8
    ## 2302     47165   7
    ## 2303     47167   7
    ## 2304     47169   1
    ## 2305     47171   3
    ## 2306     47173   3
    ## 2307     47175   1
    ## 2308     47177   4
    ## 2309     47179   8
    ## 2310     47181   6
    ## 2311     47183   7
    ## 2312     47185   4
    ## 2313     47187  11
    ## 2314     47189   4
    ## 2315     48001   8
    ## 2316     48003   1
    ## 2317     48005   6
    ## 2318     48007   2
    ## 2319     48009   5
    ## 2320     48011   2
    ## 2321     48013   9
    ## 2322     48015   7
    ## 2323     48017   3
    ## 2324     48019   5
    ## 2325     48021   8
    ## 2326     48023   1
    ## 2327     48025   9
    ## 2328     48027  18
    ## 2329     48029  70
    ## 2330     48031   4
    ## 2331     48033   1
    ## 2332     48035   8
    ## 2333     48037   9
    ## 2334     48039  15
    ## 2335     48041   7
    ## 2336     48043   5
    ## 2337     48045   2
    ## 2338     48047   2
    ## 2339     48049   7
    ## 2340     48051   3
    ## 2341     48053   4
    ## 2342     48055   7
    ## 2343     48057   4
    ## 2344     48059   4
    ## 2345     48061  16
    ## 2346     48063   2
    ## 2347     48065   4
    ## 2348     48067  10
    ## 2349     48069   4
    ## 2350     48071   7
    ## 2351     48073   8
    ## 2352     48075   2
    ## 2353     48077   4
    ## 2354     48079   3
    ## 2355     48081   4
    ## 2356     48083  10
    ## 2357     48085  26
    ## 2358     48087   3
    ## 2359     48089  12
    ## 2360     48091   7
    ## 2361     48093   5
    ## 2362     48095   3
    ## 2363     48097   7
    ## 2364     48099  10
    ## 2365     48101   1
    ## 2366     48103   1
    ## 2367     48105   1
    ## 2368     48107   3
    ## 2369     48109   1
    ## 2370     48111   3
    ## 2371     48113  82
    ## 2372     48115   2
    ## 2373     48117   2
    ## 2374     48119   6
    ## 2375     48121  26
    ## 2376     48123   4
    ## 2377     48125   4
    ## 2378     48127   4
    ## 2379     48129   3
    ## 2380     48131   5
    ## 2381     48133   8
    ## 2382     48135   8
    ## 2383     48137   2
    ## 2384     48139  13
    ## 2385     48141  30
    ## 2386     48143   4
    ## 2387     48145   6
    ## 2388     48147  14
    ## 2389     48149   9
    ## 2390     48151   4
    ## 2391     48153   4
    ## 2392     48155   1
    ## 2393     48157  21
    ## 2394     48159   2
    ## 2395     48161   6
    ## 2396     48163   4
    ## 2397     48165   3
    ## 2398     48167  17
    ## 2399     48169   2
    ## 2400     48171   5
    ## 2401     48173   1
    ## 2402     48175   3
    ## 2403     48177   8
    ## 2404     48179   3
    ## 2405     48181  17
    ## 2406     48183   9
    ## 2407     48185   7
    ## 2408     48187   7
    ## 2409     48189   6
    ## 2410     48191   4
    ## 2411     48193   4
    ## 2412     48195   3
    ## 2413     48197   2
    ## 2414     48199   9
    ## 2415     48201 130
    ## 2416     48203   7
    ## 2417     48205   2
    ## 2418     48207   6
    ## 2419     48209   7
    ## 2420     48211   1
    ## 2421     48213  11
    ## 2422     48215  27
    ## 2423     48217  15
    ## 2424     48219   7
    ## 2425     48221   4
    ## 2426     48223   8
    ## 2427     48225   6
    ## 2428     48227   4
    ## 2429     48229   4
    ## 2430     48231   9
    ## 2431     48233   4
    ## 2432     48235   2
    ## 2433     48237   4
    ## 2434     48239   7
    ## 2435     48241   5
    ## 2436     48243   2
    ## 2437     48245  17
    ## 2438     48247   1
    ## 2439     48249   5
    ## 2440     48251  11
    ## 2441     48253   6
    ## 2442     48255   7
    ## 2443     48257   8
    ## 2444     48259   4
    ## 2445     48261   1
    ## 2446     48263   2
    ## 2447     48265   5
    ## 2448     48267   3
    ## 2449     48269   1
    ## 2450     48271   1
    ## 2451     48273   2
    ## 2452     48275   4
    ## 2453     48277  11
    ## 2454     48279   7
    ## 2455     48281   3
    ## 2456     48283   3
    ## 2457     48285   5
    ## 2458     48287   5
    ## 2459     48289   8
    ## 2460     48291   9
    ## 2461     48293   7
    ## 2462     48295   5
    ## 2463     48297   3
    ## 2464     48299   8
    ## 2465     48301   1
    ## 2466     48303  20
    ## 2467     48305   3
    ## 2468     48307   6
    ## 2469     48309  24
    ## 2470     48311   2
    ## 2471     48313   3
    ## 2472     48315   2
    ## 2473     48317   4
    ## 2474     48319   4
    ## 2475     48321  10
    ## 2476     48323   3
    ## 2477     48325   9
    ## 2478     48327   3
    ## 2479     48329   5
    ## 2480     48331   6
    ## 2481     48333   3
    ## 2482     48335   3
    ## 2483     48337   7
    ## 2484     48339  21
    ## 2485     48341   3
    ## 2486     48343   4
    ## 2487     48345   3
    ## 2488     48347  11
    ## 2489     48349  12
    ## 2490     48351   6
    ## 2491     48353   5
    ## 2492     48355  24
    ## 2493     48357   3
    ## 2494     48359   4
    ## 2495     48361   4
    ## 2496     48363   7
    ## 2497     48365   5
    ## 2498     48367  10
    ## 2499     48369   4
    ## 2500     48371   5
    ## 2501     48373   7
    ## 2502     48375  10
    ## 2503     48377   3
    ## 2504     48379   2
    ## 2505     48381   8
    ## 2506     48383   1
    ## 2507     48385   3
    ## 2508     48387   6
    ## 2509     48389   4
    ## 2510     48391   5
    ## 2511     48393   1
    ## 2512     48395   5
    ## 2513     48397   4
    ## 2514     48399   5
    ## 2515     48401   7
    ## 2516     48403   4
    ## 2517     48405   2
    ## 2518     48407   5
    ## 2519     48409   9
    ## 2520     48411   3
    ## 2521     48413   1
    ## 2522     48415   4
    ## 2523     48417   2
    ## 2524     48419   5
    ## 2525     48421   1
    ## 2526     48423  16
    ## 2527     48425   3
    ## 2528     48427   8
    ## 2529     48429   2
    ## 2530     48431   1
    ## 2531     48433   2
    ## 2532     48435   1
    ## 2533     48437   3
    ## 2534     48439  65
    ## 2535     48441  15
    ## 2536     48443   2
    ## 2537     48445   3
    ## 2538     48447   2
    ## 2539     48449   4
    ## 2540     48451  11
    ## 2541     48453  47
    ## 2542     48455   4
    ## 2543     48457   8
    ## 2544     48459   5
    ## 2545     48461   3
    ## 2546     48463   6
    ## 2547     48465   4
    ## 2548     48467   7
    ## 2549     48469  10
    ## 2550     48471   6
    ## 2551     48473   5
    ## 2552     48475   5
    ## 2553     48477   4
    ## 2554     48479   9
    ## 2555     48481  11
    ## 2556     48483   5
    ## 2557     48485  11
    ## 2558     48487   4
    ## 2559     48489   6
    ## 2560     48491  20
    ## 2561     48493   6
    ## 2562     48495   2
    ## 2563     48497   8
    ## 2564     48499   6
    ## 2565     48501   3
    ## 2566     48503   5
    ## 2567     48505   3
    ## 2568     48507   3
    ## 2569     49001   4
    ## 2570     49003  18
    ## 2571     49005  17
    ## 2572     49007   6
    ## 2573     49009   2
    ## 2574     49011  11
    ## 2575     49013  12
    ## 2576     49015   9
    ## 2577     49017   9
    ## 2578     49019   2
    ## 2579     49021  10
    ## 2580     49023   4
    ## 2581     49025   7
    ## 2582     49027  10
    ## 2583     49029   2
    ## 2584     49031   5
    ## 2585     49033   4
    ## 2586     49035  37
    ## 2587     49037   7
    ## 2588     49039  15
    ## 2589     49041  12
    ## 2590     49043   8
    ## 2591     49045   8
    ## 2592     49047   7
    ## 2593     49049  22
    ## 2594     49051   3
    ## 2595     49053  20
    ## 2596     49055   6
    ## 2597     49057   9
    ## 2598     50001  15
    ## 2599     50003  16
    ## 2600     50005  17
    ## 2601     50007  18
    ## 2602     50009  11
    ## 2603      5001  10
    ## 2604     50011  15
    ## 2605     50013   5
    ## 2606     50015  11
    ## 2607     50017  24
    ## 2608     50019  22
    ## 2609     50021  25
    ## 2610     50023  20
    ## 2611     50025  23
    ## 2612     50027  30
    ## 2613      5003   7
    ## 2614      5005  10
    ## 2615      5007  17
    ## 2616      5009   5
    ## 2617      5011   4
    ## 2618      5013   4
    ## 2619      5015   6
    ## 2620      5017   3
    ## 2621      5019   7
    ## 2622      5021  11
    ## 2623      5023  10
    ## 2624      5025   3
    ## 2625      5027   5
    ## 2626      5029   9
    ## 2627      5031  12
    ## 2628      5033  10
    ## 2629      5035   9
    ## 2630      5037   4
    ## 2631      5039   3
    ## 2632      5041   8
    ## 2633      5043   3
    ## 2634      5045  11
    ## 2635      5047   5
    ## 2636      5049   9
    ## 2637      5051   8
    ## 2638      5053   5
    ## 2639      5055   5
    ## 2640      5057   7
    ## 2641      5059   3
    ## 2642      5061   4
    ## 2643      5063  14
    ## 2644      5065  15
    ## 2645      5067   7
    ## 2646      5069  10
    ## 2647      5071   8
    ## 2648      5073   4
    ## 2649      5075  13
    ## 2650      5077   5
    ## 2651      5079   3
    ## 2652      5081   6
    ## 2653      5083   9
    ## 2654      5085  10
    ## 2655      5087   8
    ## 2656      5089   8
    ## 2657      5091   4
    ## 2658      5093  14
    ## 2659      5095   5
    ## 2660      5097   7
    ## 2661      5099   4
    ## 2662     51001  33
    ## 2663     51003  13
    ## 2664     51005   5
    ## 2665     51007   2
    ## 2666     51009   4
    ## 2667      5101  11
    ## 2668     51011   3
    ## 2669     51013  11
    ## 2670     51015  18
    ## 2671     51017   5
    ## 2672     51019  10
    ## 2673     51021   4
    ## 2674     51023   7
    ## 2675     51025  12
    ## 2676     51027  12
    ## 2677     51029   6
    ## 2678      5103   5
    ## 2679     51031   7
    ## 2680     51033   6
    ## 2681     51035   8
    ## 2682     51036   1
    ## 2683     51037  10
    ## 2684     51041  13
    ## 2685     51043   5
    ## 2686     51045   2
    ## 2687     51047  13
    ## 2688     51049   2
    ## 2689      5105   6
    ## 2690     51051   8
    ## 2691     51053   7
    ## 2692     51057   8
    ## 2693     51059  42
    ## 2694     51061  16
    ## 2695     51063   5
    ## 2696     51065   5
    ## 2697     51067  10
    ## 2698     51069  10
    ## 2699      5107  10
    ## 2700     51071   9
    ## 2701     51073   3
    ## 2702     51075   8
    ## 2703     51077   6
    ## 2704     51079   4
    ## 2705     51081   3
    ## 2706     51083   9
    ## 2707     51085   8
    ## 2708     51087  13
    ## 2709     51089   8
    ## 2710      5109   7
    ## 2711     51091   5
    ## 2712     51093   6
    ## 2713     51095   3
    ## 2714     51097  10
    ## 2715     51099   2
    ## 2716     51101   4
    ## 2717     51103   5
    ## 2718     51105   8
    ## 2719     51107  17
    ## 2720     51109   4
    ## 2721      5111   8
    ## 2722     51111   3
    ## 2723     51113  13
    ## 2724     51115  17
    ## 2725     51117  10
    ## 2726     51119  11
    ## 2727     51121   6
    ## 2728     51125  12
    ## 2729     51127   5
    ## 2730      5113   6
    ## 2731     51131  12
    ## 2732     51133   7
    ## 2733     51135   3
    ## 2734     51137   6
    ## 2735     51139   4
    ## 2736     51141   7
    ## 2737     51143  14
    ## 2738     51145   2
    ## 2739     51147   7
    ## 2740     51149   4
    ## 2741      5115   8
    ## 2742     51153  16
    ## 2743     51155   6
    ## 2744     51157   7
    ## 2745     51159   3
    ## 2746     51161   6
    ## 2747     51163  10
    ## 2748     51165  17
    ## 2749     51167   6
    ## 2750     51169   7
    ## 2751      5117   5
    ## 2752     51171  11
    ## 2753     51173   5
    ## 2754     51175   8
    ## 2755     51177   5
    ## 2756     51179   4
    ## 2757     51181   5
    ## 2758     51183   6
    ## 2759     51185  16
    ## 2760     51187   3
    ## 2761      5119  22
    ## 2762     51191   7
    ## 2763     51193   5
    ## 2764     51195   7
    ## 2765     51197   8
    ## 2766     51199   6
    ## 2767      5121   7
    ## 2768      5123  10
    ## 2769      5125  10
    ## 2770      5127   4
    ## 2771      5129   7
    ## 2772      5131  13
    ## 2773      5133   5
    ## 2774      5135   7
    ## 2775      5137   7
    ## 2776      5139   8
    ## 2777      5141   6
    ## 2778      5143  15
    ## 2779      5145  15
    ## 2780      5147   6
    ## 2781      5149  10
    ## 2782     51510   6
    ## 2783     51520   1
    ## 2784     51530   1
    ## 2785     51540   2
    ## 2786     51550   6
    ## 2787     51570   1
    ## 2788     51590   2
    ## 2789     51610   1
    ## 2790     51620   1
    ## 2791     51630   1
    ## 2792     51640   1
    ## 2793     51650   6
    ## 2794     51660   3
    ## 2795     51670   1
    ## 2796     51680   4
    ## 2797     51683   1
    ## 2798     51700   8
    ## 2799     51710  14
    ## 2800     51720   1
    ## 2801     51730   2
    ## 2802     51735   1
    ## 2803     51740   7
    ## 2804     51750   2
    ## 2805     51760   8
    ## 2806     51770   7
    ## 2807     51775   1
    ## 2808     51790   1
    ## 2809     51800   7
    ## 2810     51810  12
    ## 2811     51820   1
    ## 2812     51830   1
    ## 2813     51840   1
    ## 2814     53001   5
    ## 2815     53003   3
    ## 2816     53005  10
    ## 2817     53007  13
    ## 2818     53009   9
    ## 2819     53011  19
    ## 2820     53013   2
    ## 2821     53015  10
    ## 2822     53017   7
    ## 2823     53019   8
    ## 2824     53021   5
    ## 2825     53023   1
    ## 2826     53025  16
    ## 2827     53027  19
    ## 2828     53029   8
    ## 2829     53031   7
    ## 2830     53033  83
    ## 2831     53035  18
    ## 2832     53037  10
    ## 2833     53039  14
    ## 2834     53041  19
    ## 2835     53043  12
    ## 2836     53045   9
    ## 2837     53047  19
    ## 2838     53049  10
    ## 2839     53051   6
    ## 2840     53053  56
    ## 2841     53055   9
    ## 2842     53057  14
    ## 2843     53059   4
    ## 2844     53061  28
    ## 2845     53063  36
    ## 2846     53065  19
    ## 2847     53067  12
    ## 2848     53069   4
    ## 2849     53071   7
    ## 2850     53073  15
    ## 2851     53075  21
    ## 2852     53077  21
    ## 2853     54001   6
    ## 2854     54003   9
    ## 2855     54005  27
    ## 2856     54007  11
    ## 2857     54009   6
    ## 2858     54011  10
    ## 2859     54013   9
    ## 2860     54015  13
    ## 2861     54017   4
    ## 2862     54019  39
    ## 2863     54021   9
    ## 2864     54023   7
    ## 2865     54025  17
    ## 2866     54027  17
    ## 2867     54029   5
    ## 2868     54031   7
    ## 2869     54033  17
    ## 2870     54035  11
    ## 2871     54037   8
    ## 2872     54039  41
    ## 2873     54041   9
    ## 2874     54043  13
    ## 2875     54045  29
    ## 2876     54047  32
    ## 2877     54049  13
    ## 2878     54051   8
    ## 2879     54053  13
    ## 2880     54055  17
    ## 2881     54057   8
    ## 2882     54059  18
    ## 2883     54061   9
    ## 2884     54063   9
    ## 2885     54065   2
    ## 2886     54067  13
    ## 2887     54069   4
    ## 2888     54071   7
    ## 2889     54073   2
    ## 2890     54075  11
    ## 2891     54077  13
    ## 2892     54079  11
    ## 2893     54081  39
    ## 2894     54083  21
    ## 2895     54085  10
    ## 2896     54087   8
    ## 2897     54089   9
    ## 2898     54091   5
    ## 2899     54093   5
    ## 2900     54095   4
    ## 2901     54097   6
    ## 2902     54099  13
    ## 2903     54101   9
    ## 2904     54103  10
    ## 2905     54105   4
    ## 2906     54107  11
    ## 2907     54109  34
    ## 2908     55001   5
    ## 2909     55003   9
    ## 2910     55005  13
    ## 2911     55007  10
    ## 2912     55009  15
    ## 2913     55011   5
    ## 2914     55013   5
    ## 2915     55015   8
    ## 2916     55017   9
    ## 2917     55019  15
    ## 2918     55021  12
    ## 2919     55023   9
    ## 2920     55025  36
    ## 2921     55027  21
    ## 2922     55029  10
    ## 2923     55031  10
    ## 2924     55033  10
    ## 2925     55035   7
    ## 2926     55037   3
    ## 2927     55039  14
    ## 2928     55041   5
    ## 2929     55043  20
    ## 2930     55045   7
    ## 2931     55047   7
    ## 2932     55049  11
    ## 2933     55051   7
    ## 2934     55053   7
    ## 2935     55055  10
    ## 2936     55057   8
    ## 2937     55059  11
    ## 2938     55061   4
    ## 2939     55063   8
    ## 2940     55065   9
    ## 2941     55067   9
    ## 2942     55069   4
    ## 2943     55071  13
    ## 2944     55073  15
    ## 2945     55075  13
    ## 2946     55077   6
    ## 2947     55078   2
    ## 2948     55079  36
    ## 2949     55081   7
    ## 2950     55083  11
    ## 2951     55085   8
    ## 2952     55087  15
    ## 2953     55089   8
    ## 2954     55091   4
    ## 2955     55093  11
    ## 2956     55095  13
    ## 2957     55097  11
    ## 2958     55099   8
    ## 2959     55101  13
    ## 2960     55103   6
    ## 2961     55105  11
    ## 2962     55107   8
    ## 2963     55109  11
    ## 2964     55111  13
    ## 2965     55113   7
    ## 2966     55115  13
    ## 2967     55117  14
    ## 2968     55119   6
    ## 2969     55121  11
    ## 2970     55123  11
    ## 2971     55125  12
    ## 2972     55127  12
    ## 2973     55129   7
    ## 2974     55131  11
    ## 2975     55133  26
    ## 2976     55135  12
    ## 2977     55137   8
    ## 2978     55139  13
    ## 2979     55141  13
    ## 2980     56001   8
    ## 2981     56003  13
    ## 2982     56005   6
    ## 2983     56007  10
    ## 2984     56009   3
    ## 2985     56011   7
    ## 2986     56013  11
    ## 2987     56015   8
    ## 2988     56017   2
    ## 2989     56019   3
    ## 2990     56021  10
    ## 2991     56023  16
    ## 2992     56025   9
    ## 2993     56027   5
    ## 2994     56029   6
    ## 2995     56031   5
    ## 2996     56033  12
    ## 2997     56035   6
    ## 2998     56037  11
    ## 2999     56039   7
    ## 3000     56041   6
    ## 3001     56043   2
    ## 3002     56045   3
    ## 3003      6001  49
    ## 3004      6003   2
    ## 3005      6005  11
    ## 3006      6007  16
    ## 3007      6009  19
    ## 3008      6011   7
    ## 3009      6013  42
    ## 3010      6015   4
    ## 3011      6017  21
    ## 3012      6019  54
    ## 3013      6021   6
    ## 3014      6023  35
    ## 3015      6025  14
    ## 3016      6027  11
    ## 3017      6029  50
    ## 3018      6031   7
    ## 3019      6033  14
    ## 3020      6035  14
    ## 3021      6037 281
    ## 3022      6039  12
    ## 3023      6041  29
    ## 3024      6043   8
    ## 3025      6045  25
    ## 3026      6047  19
    ## 3027      6049  11
    ## 3028      6051   7
    ## 3029      6053  29
    ## 3030      6055  10
    ## 3031      6057   9
    ## 3032      6059  88
    ## 3033      6061  29
    ## 3034      6063  15
    ## 3035      6065  70
    ## 3036      6067  54
    ## 3037      6069   4
    ## 3038      6071  87
    ## 3039      6073 106
    ## 3040      6075  27
    ## 3041      6077  32
    ## 3042      6079  20
    ## 3043      6081  30
    ## 3044      6083  23
    ## 3045      6085  56
    ## 3046      6087  17
    ## 3047      6089  25
    ## 3048      6091   8
    ## 3049      6093  23
    ## 3050      6095  15
    ## 3051      6097  34
    ## 3052      6099  24
    ## 3053      6101   8
    ## 3054      6103  13
    ## 3055      6105  13
    ## 3056      6107  33
    ## 3057      6109  12
    ## 3058      6111  25
    ## 3059      6113  18
    ## 3060      6115  11
    ## 3061      8001  17
    ## 3062      8003   3
    ## 3063      8005  20
    ## 3064      8007   3
    ## 3065      8009   6
    ## 3066      8011   4
    ## 3067      8013  17
    ## 3068      8014   2
    ## 3069      8015   4
    ## 3070      8017   4
    ## 3071      8019   5
    ## 3072      8021   7
    ## 3073      8023   5
    ## 3074      8025   4
    ## 3075      8027   2
    ## 3076      8029   7
    ## 3077      8031  25
    ## 3078      8033   3
    ## 3079      8035  14
    ## 3080      8037  11
    ## 3081      8039   5
    ## 3082      8041  43
    ## 3083      8043   9
    ## 3084      8045   6
    ## 3085      8047   2
    ## 3086      8049   8
    ## 3087      8051  11
    ## 3088      8053   1
    ## 3089      8055   3
    ## 3090      8057   3
    ## 3091      8059  28
    ## 3092      8061   4
    ## 3093      8063   6
    ## 3094      8065   2
    ## 3095      8067   5
    ## 3096      8069  18
    ## 3097      8071   8
    ## 3098      8073   5
    ## 3099      8075   8
    ## 3100      8077  17
    ## 3101      8079   1
    ## 3102      8081   5
    ## 3103      8083   8
    ## 3104      8085   8
    ## 3105      8087   8
    ## 3106      8089   6
    ## 3107      8091   2
    ## 3108      8093  10
    ## 3109      8095   4
    ## 3110      8097   5
    ## 3111      8099   5
    ## 3112      8101  12
    ## 3113      8103   2
    ## 3114      8105   3
    ## 3115      8107  10
    ## 3116      8109   6
    ## 3117      8111   1
    ## 3118      8113   5
    ## 3119      8115   3
    ## 3120      8117   5
    ## 3121      8119   5
    ## 3122      8121   6
    ## 3123      8123  32
    ## 3124      8125   7
    ## 3125      9001  47
    ## 3126      9003  57
    ## 3127      9005  38
    ## 3128      9007  22
    ## 3129      9009  41
    ## 3130      9011  31
    ## 3131      9013  15
    ## 3132      9015  27

``` r
#Each row is a ZIP code and so counting the COUNTY.NAME will show how many ZIP is in each county in each State.
usage_ZIP_2020 %>% group_by(ST) %>% count(COUNTY.NAME)
```

    ## # A tibble: 3,132 x 3
    ## # Groups:   ST [51]
    ##    ST    COUNTY.NAME                      n
    ##    <chr> <chr>                        <int>
    ##  1 AK    Aleutians East Borough           5
    ##  2 AK    Aleutians West Census Area       7
    ##  3 AK    Anchorage Municipality          16
    ##  4 AK    Bethel Census Area              26
    ##  5 AK    Bristol Bay Borough              3
    ##  6 AK    Denali Borough                   5
    ##  7 AK    Dillingham Census Area           7
    ##  8 AK    Fairbanks North Star Borough     8
    ##  9 AK    Haines Borough                   1
    ## 10 AK    Hoonah-Angoon Census Area        6
    ## # ... with 3,122 more rows

``` r
length(unique(usage_ZIP_2020$ZIP))
```

    ## [1] 32653
